package com.enigma.familylinklite;

import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.content.pm.*;import android.app.usage.*;import android.media.*;import android.net.wifi.WifiManager;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import javax.crypto.*;import javax.crypto.spec.*;

public class ChildServerService extends Service{
    static final int PORT=45454; static final String CHANNEL="child_server"; volatile boolean running=false; volatile boolean alarm=false; ServerSocket serverSocket; ToneGenerator tone; byte[] key; Thread serverThread; Thread discoveryThread; WifiManager.WifiLock wifiLock; PowerManager.WakeLock wakeLock; Map<String,Long> blockedIps=new HashMap<>(); Set<String> recentCommands=Collections.synchronizedSet(new LinkedHashSet<String>()); static final int PROTOCOL_VERSION=7; static final int MIN_PROTOCOL=2; static final String APP_VERSION="1.1"; static final String CAPABILITIES="ping,message,volume,usage,current_app,app_block,lock_screen,lock_timeout,device_admin,accessibility_blocking,version,command_ids,replay_protection,update_prompt,profiles,second_parent_scaffold";
    public IBinder onBind(Intent i){return null;}
    public int onStartCommand(Intent intent,int flags,int startId){
        try{key=Base64.getDecoder().decode(getSharedPreferences("p",0).getString("key", ""));}catch(Exception e){broadcast("No pairing key found. Open Child mode once.");stopSelf();return START_NOT_STICKY;}
        startForeground(1, notification("FamilyLink child server running", "Listening on port "+PORT));
        acquireLocks();
        if(serverThread==null||!serverThread.isAlive()){running=true;serverThread=new Thread(this::runServer,"FamilyLinkChildServer");serverThread.start();startDiscovery();broadcast("Server start requested");}else broadcast("Server already running");
        return START_STICKY;
    }
    public void onCreate(){super.onCreate();createChannel();}
    public void onDestroy(){running=false;try{if(serverSocket!=null)serverSocket.close();}catch(Exception ignored){}stopAlarm();releaseLocks();super.onDestroy();}
    void acquireLocks(){try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);wifiLock=wm.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF,"FamilyLinkWifiLock");wifiLock.setReferenceCounted(false);wifiLock.acquire();}catch(Exception e){broadcast("Wi-Fi lock unavailable: "+e.getMessage());}try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wakeLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"FamilyLink:ChildServer");wakeLock.setReferenceCounted(false);wakeLock.acquire();}catch(Exception e){broadcast("Wake lock unavailable: "+e.getMessage());}}
    void releaseLocks(){try{if(wifiLock!=null&&wifiLock.isHeld())wifiLock.release();}catch(Exception ignored){}try{if(wakeLock!=null&&wakeLock.isHeld())wakeLock.release();}catch(Exception ignored){}}
    void runServer(){
        try{serverSocket=new ServerSocket();serverSocket.setReuseAddress(true);serverSocket.bind(new InetSocketAddress(PORT));broadcast("Server running in background on port "+PORT);while(running){Socket s=serverSocket.accept();handleSocket(s);}}
        catch(BindException e){broadcast("Server already active on port "+PORT+". Force stop the app if commands fail.");}
        catch(Exception e){if(running)broadcast("Server stopped: "+e.getMessage());}
    }
    void handleSocket(Socket s){String ip="";try{ip=s.getInetAddress().getHostAddress();Long until=blockedIps.get(ip);if(until!=null&&until>System.currentTimeMillis()){s.close();return;}BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String line=r.readLine();PrintWriter w=new PrintWriter(s.getOutputStream(),true);if(line!=null&&line.startsWith("PAIR|")){w.println(handlePair(line,ip));s.close();return;}String json;try{json=decrypt(line);}catch(Exception bad){blockedIps.put(ip,System.currentTimeMillis()+60000);broadcast("Bad handshake from "+ip+". Blocked for 60 seconds.");s.close();return;}String resp=handle(new JSONObject(json));w.println(encrypt(resp));s.close();}catch(Exception e){try{s.close();}catch(Exception ignored){}broadcast("Command error: "+e.getMessage());}}

    void startDiscovery(){if(discoveryThread!=null&&discoveryThread.isAlive())return;discoveryThread=new Thread(()->{int[] burst={0,5,15};for(int delay:burst){if(!running)return;try{Thread.sleep(delay*1000L);}catch(Exception ignored){}sendDiscovery();}while(running){try{Thread.sleep(60000);}catch(Exception ignored){}sendDiscovery();}},"FamilyLinkDiscovery");discoveryThread.start();}
    void sendDiscovery(){try{String payload="FLITE|1|"+PORT+"|"+pairingId();byte[] data=payload.getBytes(StandardCharsets.UTF_8);DatagramSocket ds=new DatagramSocket();ds.setBroadcast(true);DatagramPacket p=new DatagramPacket(data,data.length,InetAddress.getByName("255.255.255.255"),45455);ds.send(p);ds.close();}catch(Exception e){broadcast("Discovery broadcast failed: "+e.getMessage());}}
    String pairingId(){try{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] h=md.digest(key);return Base64.getEncoder().encodeToString(Arrays.copyOf(h,9));}catch(Exception e){return "unknown";}}
    String handlePair(String line,String ip){try{String[] p=line.split("\\|");String code=p.length>1?p[1].replaceAll("\\D",""):"";if(code.equals(currentPairCode(key))){broadcast("Pairing approved for "+ip);return "OK|"+Base64.getEncoder().encodeToString(key)+"|"+pairingId()+"|"+APP_VERSION+"|"+PROTOCOL_VERSION+"|"+MIN_PROTOCOL+"|"+CAPABILITIES;}blockedIps.put(ip,System.currentTimeMillis()+60000);broadcast("Wrong pairing code from "+ip+". Blocked for 60 seconds.");return "NO|wrong-code";}catch(Exception e){return "NO|"+e.getMessage();}}
    static String currentPairCode(byte[] k){try{long slice=System.currentTimeMillis()/120000L;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(k,"HmacSHA256"));byte[] h=mac.doFinal(String.valueOf(slice).getBytes(StandardCharsets.UTF_8));int n=((h[0]&0xff)<<16)|((h[1]&0xff)<<8)|(h[2]&0xff);return String.format(Locale.US,"%06d",Math.abs(n)%1000000);}catch(Exception e){return "000000";}}
    String handle(JSONObject j)throws Exception{int otherProtocol=j.optInt("protocol",1);int otherMin=j.optInt("minProtocol",1);if(PROTOCOL_VERSION<otherMin||otherProtocol<MIN_PROTOCOL)return "Update required: incompatible protocol";String commandId=j.optString("id","");if(commandId.length()>0){if(recentCommands.contains(commandId))return "Duplicate command ignored";recentCommands.add(commandId);if(recentCommands.size()>200){Iterator<String> it=recentCommands.iterator();if(it.hasNext()){it.next();it.remove();}}}String type=j.optString("type"),value=j.optString("value");if(type.equals("message")){showCommandNotification("Message from parent",value);return "Message shown";}if(type.equals("ping")){if(value.equals("start"))startAlarm();else stopAlarm();return "Ping "+value;}if(type.equals("volume")){setMediaVol(Integer.parseInt(value));return "Volume set to "+value+"%";}if(type.equals("hello")){return "VERSION: "+APP_VERSION+"\nPROTOCOL: "+PROTOCOL_VERSION+"\nCAPABILITIES: "+CAPABILITIES+"\n";}if(type.equals("usage")){return usageToday();}if(type.equals("current_app")){return "CURRENT_APP: "+currentApp();}if(type.equals("block_current")){String app=currentPackage();if(app.length()==0)return "No current app detected. Enable Usage Access on the tablet.";long until=System.currentTimeMillis()+24L*60L*60000L;getSharedPreferences("rules",0).edit().putLong("blocked_until_"+app,until).apply();showCommandNotification("App blocked", app+" blocked until tomorrow. Accessibility blocking will push it away when opened.");return "Blocked current app until tomorrow: "+app;}if(type.equals("lock_screen")){return lockNow("Parent requested screen lock");}if(type.equals("lock_timeout")){int mins=0;try{mins=Integer.parseInt(value.trim());}catch(Exception ignored){}long until=System.currentTimeMillis()+Math.max(1,mins)*60000L;getSharedPreferences("rules",0).edit().putLong("lock_until",until).apply();String lockResult=lockNow("Timeout for "+Math.max(1,mins)+" minutes");showCommandNotification("Tablet timeout", "Timeout active for "+Math.max(1,mins)+" minutes.");return "Lock timeout active for "+Math.max(1,mins)+" minutes. "+lockResult;}if(type.equals("update_prompt")){showCommandNotification("FamilyLink update", "Parent requests update to "+(value.length()>0?value:"the latest version")+". Open the parent release page and install when available.");return "Update prompt shown";}if(type.equals("profile")){return applyProfile(value);}return "Unknown command";}
    String applyProfile(String value){String profile=value==null?"":value.trim();SharedPreferences.Editor ed=getSharedPreferences("rules",0).edit();long now=System.currentTimeMillis();if(profile.equals("homework")){ed.putString("active_profile","homework").putLong("profile_until",now+2L*60L*60L*1000L).apply();showCommandNotification("Homework mode", "Homework mode active. Entertainment apps can be blocked in the next rules update.");return "Homework profile active";}if(profile.equals("bedtime")){ed.putString("active_profile","bedtime").putLong("profile_until",now+8L*60L*60L*1000L).putLong("lock_until",now+8L*60L*60L*1000L).apply();showCommandNotification("Bedtime mode", "Bedtime mode active.");return "Bedtime profile active";}if(profile.equals("free_time")){ed.putString("active_profile","free_time").remove("lock_until").apply();showCommandNotification("Free time", "Restrictions relaxed.");return "Free time profile active";}return "Unknown profile";}

    String lockNow(String reason){try{DevicePolicyManager dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName admin=new ComponentName(this,AdminReceiver.class);if(dpm!=null&&dpm.isAdminActive(admin)){dpm.lockNow();broadcast("Screen locked: "+reason);return "Screen locked";}showCommandNotification("Device admin needed", "Enable Device Admin for real screen lock.");return "Device admin not enabled; cannot lock screen";}catch(Exception e){return "Lock failed: "+e.getMessage();}}
    void setMediaVol(int percent){AudioManager a=(AudioManager)getSystemService(AUDIO_SERVICE);int max=a.getStreamMaxVolume(AudioManager.STREAM_MUSIC);int v=Math.max(0,Math.min(max,Math.round(max*percent/100f)));a.setStreamVolume(AudioManager.STREAM_MUSIC,v,0);}
    void startAlarm(){alarm=true;if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_ALARM,100);showCommandNotification("Parent is pinging", "Open the app or use Stop ping from parent to stop it.");new Thread(()->{while(alarm){tone.startTone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD,700);try{Thread.sleep(900);}catch(Exception ignored){}}}).start();}
    void stopAlarm(){alarm=false;if(tone!=null)tone.stopTone();}
    String currentApp(){String pkg=currentPackage();if(pkg.length()==0)return "Unavailable. Enable Usage Access on the tablet.";try{PackageManager pm=getPackageManager();ApplicationInfo ai=pm.getApplicationInfo(pkg,0);return pm.getApplicationLabel(ai).toString()+" ("+pkg+")";}catch(Exception e){return pkg;}}
    String currentPackage(){try{UsageStatsManager us=(UsageStatsManager)getSystemService(USAGE_STATS_SERVICE);long end=System.currentTimeMillis();long start=end-5*60*1000;UsageEvents events=us.queryEvents(start,end);UsageEvents.Event ev=new UsageEvents.Event();String last="";long lastTime=0;while(events.hasNextEvent()){events.getNextEvent(ev);if(ev.getEventType()==UsageEvents.Event.MOVE_TO_FOREGROUND||ev.getEventType()==UsageEvents.Event.ACTIVITY_RESUMED){if(ev.getTimeStamp()>lastTime){lastTime=ev.getTimeStamp();last=ev.getPackageName();}}}return last==null?"":last;}catch(Exception e){return "";}}
    String usageToday(){try{UsageStatsManager us=(UsageStatsManager)getSystemService(USAGE_STATS_SERVICE);Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);List<UsageStats> stats=us.queryUsageStats(UsageStatsManager.INTERVAL_DAILY,c.getTimeInMillis(),System.currentTimeMillis());PackageManager pm=getPackageManager();stats.sort((a,b)->Long.compare(b.getTotalTimeInForeground(),a.getTotalTimeInForeground()));StringBuilder sb=new StringBuilder("VERSION: "+APP_VERSION+"\nPROTOCOL: "+PROTOCOL_VERSION+"\nCAPABILITIES: "+CAPABILITIES+"\nUsage today:\n");int n=0;for(UsageStats st:stats){long mins=st.getTotalTimeInForeground()/60000;if(mins<1)continue;String name=st.getPackageName();try{ApplicationInfo ai=pm.getApplicationInfo(name,0);name=pm.getApplicationLabel(ai).toString();}catch(Exception ignored){}sb.append(name).append(": ").append(mins).append(" min\n");if(++n>=20)break;}if(n==0)sb.append("No usage data found. Enable Usage Access on the tablet.\n");return sb.toString();}catch(Exception e){return "Usage access not granted or unavailable: "+e.getMessage();}}
    String encrypt(String plain)throws Exception{byte[] iv=new byte[12];new SecureRandom().nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));byte[] enc=c.doFinal(plain.getBytes(StandardCharsets.UTF_8));byte[] all=new byte[iv.length+enc.length];System.arraycopy(iv,0,all,0,iv.length);System.arraycopy(enc,0,all,iv.length,enc.length);return Base64.getEncoder().encodeToString(all);} 
    String decrypt(String data)throws Exception{byte[] all=Base64.getDecoder().decode(data);byte[] iv=Arrays.copyOfRange(all,0,12);byte[] enc=Arrays.copyOfRange(all,12,all.length);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));return new String(c.doFinal(enc),StandardCharsets.UTF_8);} 
    void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"FamilyLink Child Server",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(ch);}}
    Notification notification(String title,String text){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE);return new Notification.Builder(this,CHANNEL).setContentTitle(title).setContentText(text).setSmallIcon(android.R.drawable.ic_dialog_info).setContentIntent(pi).setOngoing(true).build();}
    void showCommandNotification(String title,String text){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.notify(2,new Notification.Builder(this,CHANNEL).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setSmallIcon(android.R.drawable.ic_dialog_info).build());broadcast(title+": "+text);}
    void broadcast(String s){sendBroadcast(new Intent("com.enigma.familylinklite.LOG").putExtra("msg",s));}
}
