package com.enigma.familylinklite;

import android.app.*;import android.content.*;import android.content.pm.*;import android.app.usage.*;import android.media.*;import android.net.wifi.WifiManager;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import javax.crypto.*;import javax.crypto.spec.*;

public class ChildServerService extends Service{
    static final int PORT=45454, DISCOVERY_PORT=45455; static final String CHANNEL="child_server"; volatile boolean running=false; volatile boolean alarm=false; ServerSocket serverSocket; ToneGenerator tone; byte[] key; String childId=""; Thread serverThread,broadcastThread; WifiManager.WifiLock wifiLock; PowerManager.WakeLock wakeLock; Map<String,Long> blockedIps=Collections.synchronizedMap(new HashMap<>());
    public IBinder onBind(Intent i){return null;} public void onCreate(){super.onCreate();createChannel();}
    public int onStartCommand(Intent intent,int flags,int startId){try{key=Base64.getDecoder().decode(getSharedPreferences("p",0).getString("key", ""));childId=getSharedPreferences("p",0).getString("childId","");}catch(Exception e){broadcast("No pairing key found. Open Child mode once.");stopSelf();return START_NOT_STICKY;}startForeground(1, notification("FamilyLink child server running", "Listening on port "+PORT));acquireLocks();running=true;if(serverThread==null||!serverThread.isAlive()){serverThread=new Thread(this::runServer,"FamilyLinkChildServer");serverThread.start();broadcast("Server start requested");}else broadcast("Server already running");if(broadcastThread==null||!broadcastThread.isAlive()){broadcastThread=new Thread(this::runPresence,"FamilyLinkChildPresence");broadcastThread.start();}return START_STICKY;}
    public void onDestroy(){running=false;try{if(serverSocket!=null)serverSocket.close();}catch(Exception ignored){}stopAlarm();releaseLocks();super.onDestroy();}
    void runPresence(){long[] burst={0,5000,15000};for(long delay:burst){if(!running)return;try{Thread.sleep(delay);}catch(Exception ignored){}sendPresence();}while(running){try{Thread.sleep(60000);}catch(Exception ignored){}sendPresence();}}
    void sendPresence(){DatagramSocket ds=null;try{String msg="FAMILYLINK_CHILD|"+childId+"|"+PORT+"|v0.4";byte[] data=msg.getBytes(StandardCharsets.UTF_8);ds=new DatagramSocket();ds.setBroadcast(true);ds.send(new DatagramPacket(data,data.length,InetAddress.getByName("255.255.255.255"),DISCOVERY_PORT));broadcast("Presence broadcast sent");}catch(Exception e){broadcast("Presence broadcast failed: "+e.getMessage());}finally{if(ds!=null)ds.close();}}
    void runServer(){try{serverSocket=new ServerSocket();serverSocket.setReuseAddress(true);serverSocket.bind(new InetSocketAddress(PORT));broadcast("Server running in background on port "+PORT);while(running){Socket s=serverSocket.accept();handleSocket(s);}}catch(BindException e){broadcast("Server already active on port "+PORT+". Force stop the app if commands fail.");}catch(Exception e){if(running)broadcast("Server stopped: "+e.getMessage());}}
    void handleSocket(Socket s){String ip="";try{ip=s.getInetAddress().getHostAddress();Long until=blockedIps.get(ip);if(until!=null&&System.currentTimeMillis()<until){s.close();return;}BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String line=r.readLine();String json;try{json=decrypt(line);}catch(Exception bad){blockedIps.put(ip,System.currentTimeMillis()+60000);broadcast("Bad handshake from "+ip+". Blocked for 60 seconds.");s.close();return;}String resp=handle(new JSONObject(json));PrintWriter w=new PrintWriter(s.getOutputStream(),true);w.println(encrypt(resp));s.close();}catch(Exception e){try{s.close();}catch(Exception ignored){}broadcast("Command error from "+ip+": "+e.getMessage());}}
    String handle(JSONObject j)throws Exception{String type=j.optString("type"),value=j.optString("value");if(type.equals("message")){showCommandNotification("Message from parent",value);return "Message shown";}if(type.equals("ping")){if(value.equals("start"))startAlarm();else stopAlarm();return "Ping "+value;}if(type.equals("volume")){setMediaVol(Integer.parseInt(value));return "Volume set to "+value+"%";}if(type.equals("usage")){return usageTodayJson();}return "Unknown command";}
    void setMediaVol(int percent){AudioManager a=(AudioManager)getSystemService(AUDIO_SERVICE);int max=a.getStreamMaxVolume(AudioManager.STREAM_MUSIC);int v=Math.max(0,Math.min(max,Math.round(max*percent/100f)));a.setStreamVolume(AudioManager.STREAM_MUSIC,v,0);} void startAlarm(){alarm=true;if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_ALARM,100);showCommandNotification("Parent is pinging", "Open the app or use Stop ping from parent to stop it.");new Thread(()->{while(alarm){tone.startTone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD,700);try{Thread.sleep(900);}catch(Exception ignored){}}}).start();} void stopAlarm(){alarm=false;if(tone!=null)tone.stopTone();}
    String usageTodayJson(){try{UsageStatsManager us=(UsageStatsManager)getSystemService(USAGE_STATS_SERVICE);Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);List<UsageStats> stats=us.queryUsageStats(UsageStatsManager.INTERVAL_DAILY,c.getTimeInMillis(),System.currentTimeMillis());PackageManager pm=getPackageManager();stats.sort((a,b)->Long.compare(b.getTotalTimeInForeground(),a.getTotalTimeInForeground()));JSONArray arr=new JSONArray();long total=0;int n=0;for(UsageStats st:stats){long mins=st.getTotalTimeInForeground()/60000;if(mins<1)continue;total+=mins;String name=st.getPackageName();try{ApplicationInfo ai=pm.getApplicationInfo(name,0);name=pm.getApplicationLabel(ai).toString();}catch(Exception ignored){}JSONObject o=new JSONObject();o.put("name",name);o.put("minutes",mins);arr.put(o);if(++n>=20)break;}JSONObject out=new JSONObject();out.put("totalMinutes",total);out.put("apps",arr);return "USAGE_JSON:"+out.toString();}catch(Exception e){return "Usage access not granted or unavailable: "+e.getMessage();}}
    String encrypt(String plain)throws Exception{byte[] iv=new byte[12];new SecureRandom().nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));byte[] enc=c.doFinal(plain.getBytes(StandardCharsets.UTF_8));byte[] all=new byte[iv.length+enc.length];System.arraycopy(iv,0,all,0,iv.length);System.arraycopy(enc,0,all,iv.length,enc.length);return Base64.getEncoder().encodeToString(all);} String decrypt(String data)throws Exception{byte[] all=Base64.getDecoder().decode(data);byte[] iv=Arrays.copyOfRange(all,0,12);byte[] enc=Arrays.copyOfRange(all,12,all.length);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));return new String(c.doFinal(enc),StandardCharsets.UTF_8);} 
    void acquireLocks(){try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);wifiLock=wm.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF,"FamilyLinkWifiLock");wifiLock.setReferenceCounted(false);wifiLock.acquire();}catch(Exception e){broadcast("Wi-Fi lock unavailable: "+e.getMessage());}try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wakeLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"FamilyLink:ChildServer");wakeLock.setReferenceCounted(false);wakeLock.acquire();}catch(Exception e){broadcast("Wake lock unavailable: "+e.getMessage());}} void releaseLocks(){try{if(wifiLock!=null&&wifiLock.isHeld())wifiLock.release();}catch(Exception ignored){}try{if(wakeLock!=null&&wakeLock.isHeld())wakeLock.release();}catch(Exception ignored){}}
    void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"FamilyLink Child Server",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(ch);}} Notification notification(String title,String text){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE);return new Notification.Builder(this,CHANNEL).setContentTitle(title).setContentText(text).setSmallIcon(android.R.drawable.ic_dialog_info).setContentIntent(pi).setOngoing(true).build();} void showCommandNotification(String title,String text){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.notify(2,new Notification.Builder(this,CHANNEL).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setSmallIcon(android.R.drawable.ic_dialog_info).build());broadcast(title+": "+text);} void broadcast(String s){sendBroadcast(new Intent("com.enigma.familylinklite.LOG").putExtra("msg",s));}
}
