package com.enigma.familylinklite;

import android.Manifest;
import android.content.pm.PackageManager;
import com.enigma.familylinklite.services.ChildServerService;
import com.enigma.familylinklite.ui.screens.ChildHomeScreen;
import com.enigma.familylinklite.storage.BlockedAppEntry;
import com.enigma.familylinklite.services.ParentMonitorService;import com.enigma.familylinklite.security.CryptoUtils;import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.graphics.*;import android.media.*;import android.net.*;import android.net.wifi.WifiManager;import android.os.*;import android.provider.Settings;import android.text.*;import android.text.format.Formatter;import android.view.*;import android.widget.*;import com.enigma.familylinklite.core.AppConfig;import com.enigma.familylinklite.devices.DeviceProfile;import com.enigma.familylinklite.network.CommandClient;import com.enigma.familylinklite.storage.AppLog;import com.enigma.familylinklite.storage.SavedConnection;import com.enigma.familylinklite.ui.UiFactory;import com.enigma.familylinklite.updates.UpdateChecker;import com.enigma.familylinklite.updates.VersionUtils;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;import com.google.zxing.integration.android.IntentIntegrator;import com.google.zxing.integration.android.IntentResult;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import javax.crypto.*;import javax.crypto.spec.*;

public class MainActivity extends Activity{
    PopupWindow sidePanel; String currentScreen="";
    static final int PORT=AppConfig.COMMAND_PORT; static final int DISCOVERY_PORT=AppConfig.DISCOVERY_PORT; static final int PROTOCOL_VERSION=AppConfig.PROTOCOL_VERSION; static final int MIN_PROTOCOL=AppConfig.MIN_SUPPORTED_PROTOCOL; static final int AUTH_REQUEST=900; static final String APP_VERSION=AppConfig.APP_VERSION; static final String DEFAULT_REPO=AppConfig.DEFAULT_REPO;
    LinearLayout root; byte[] key; String childIp=""; TextView log; TextView childPairCodeView; TextView childCountdownView; ImageView childQrView; Handler handler=new Handler(Looper.getMainLooper()); BroadcastReceiver br; int parentVolume=50; Thread discoveryListenThread; boolean unlockedThisRun=false; boolean authPromptLaunched=false; boolean childPairingDetailsVisible=false;

    public void onCreate(Bundle b){super.onCreate(b); getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE); if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7); ensureIds(); handleDeepLinkOrStart();}
    void handleDeepLinkOrStart(){Uri u=getIntent()!=null?getIntent().getData():null;if(u!=null&&"family-link".equals(u.getScheme())&&"pair".equals(u.getHost())){String code=u.getQueryParameter("code");getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection(code==null?"":code);return;}showStartOrSaved();}
    void ensureIds(){SharedPreferences p=getSharedPreferences("p",0);if(p.getString("localDeviceId","").length()==0)p.edit().putString("localDeviceId",UUID.randomUUID().toString()).putString("parentName","Parent Control").apply();}
    void showStartOrSaved(){SavedConnection c=new SavedConnection(this);String role=c.role();if(c.hasParentConnection()){childIp=c.childIp();key=c.parentKeyBytesOrNull();if(!unlockedThisRun)showParentAppLock();else showConnectedParent(true);}else if(role.equals("child")){showChild();}else showStart();}
    @Override public void onBackPressed(){if(sidePanel!=null&&sidePanel.isShowing()){sidePanel.dismiss();return;}if("dashboard".equals(currentScreen)){moveTaskToBack(true);return;}SavedConnection c=new SavedConnection(this);if(c.hasParentConnection()&&unlockedThisRun){showConnectedParent(true);return;}super.onBackPressed();}
    protected void onDestroy(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}super.onDestroy();}
    protected void onActivityResult(int requestCode,int resultCode,Intent data){if(requestCode==AUTH_REQUEST){if(resultCode==RESULT_OK){unlockParentApp("biometrics");}else toast("Unlock cancelled");return;}IntentResult result=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(result!=null){if(result.getContents()!=null)handlePairQr(result.getContents().trim());else toast("QR scan cancelled");return;}super.onActivityResult(requestCode,resultCode,data);}

    TextView tv(String s,int sp){return UiFactory.text(this,s,sp);} Button btn(String s){return UiFactory.button(this,s);} EditText oneLine(String hint){return UiFactory.oneLine(this,hint);} EditText edit(String hint){return UiFactory.multiLine(this,hint);}
    void base(String title){handler.removeCallbacksAndMessages(null);root=UiFactory.attachRoot(this);SharedPreferences p=getSharedPreferences("p",0);UiFactory.addTopBar(this,root,p,v->showUserMenu());if(title!=null&&title.length()>0)root.addView(tv(title,22));log=tv("",14);}
    void fixedBase(String title){handler.removeCallbacksAndMessages(null);root=UiFactory.attachFixedRoot(this);SharedPreferences p=getSharedPreferences("p",0);UiFactory.addTopBar(this,root,p,v->showUserMenu());if(title!=null&&title.length()>0)root.addView(tv(title,22));log=tv("",14);}

    void showParentAppLock(){lockBase();SharedPreferences p=getSharedPreferences("p",0);String savedPin=p.getString("appPin","");long lockUntil=p.getLong("pinLockUntil",0);long now=System.currentTimeMillis();root.addView(tv("Parental-Link",26));root.addView(tv("Unlock parent dashboard",18));if(lockUntil>now){long sec=Math.max(1,(lockUntil-now+999)/1000);root.addView(tv("Too many wrong attempts. Try again in "+sec+" seconds.",16));handler.postDelayed(()->showParentAppLock(),Math.min(lockUntil-now,60000));return;}if(!authPromptLaunched&&canUseDeviceCredential()){authPromptLaunched=true;handler.postDelayed(()->launchDeviceCredential(),250);}if(savedPin.length()==0){showCreateParentPin(p);return;}TextView dots=tv("",32);dots.setGravity(Gravity.CENTER);root.addView(dots);final StringBuilder entered=new StringBuilder();GridLayout pad=new GridLayout(this);pad.setColumnCount(3);pad.setPadding(0,24,0,16);for(String label:new String[]{"1","2","3","4","5","6","7","8","9","⌫","0","Bio"}){Button b=btn(label);pad.addView(b,new ViewGroup.LayoutParams(getResources().getDisplayMetrics().widthPixels/3-28,130));b.setOnClickListener(v->{String t=((Button)v).getText().toString();if(t.equals("⌫")){if(entered.length()>0)entered.deleteCharAt(entered.length()-1);}else if(t.equals("Bio")){launchDeviceCredential();}else{if(entered.length()<6)entered.append(t);}StringBuilder stars=new StringBuilder();for(int i=0;i<entered.length();i++)stars.append("• ");dots.setText(stars.toString());if(entered.length()>=4&&entered.toString().equals(savedPin)){unlockParentApp("PIN");}else if(entered.length()==6&&!entered.toString().equals(savedPin)){registerWrongPinAttempt();}});}root.addView(pad);root.addView(tv("Use the number pad. Press Bio if the biometric prompt was closed.",13));}
    void lockBase(){handler.removeCallbacksAndMessages(null);root=UiFactory.attachRoot(this);root.setPadding(36,72,36,36);log=tv("",14);}    
    boolean canUseDeviceCredential(){KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);return Build.VERSION.SDK_INT>=21&&km!=null&&km.isDeviceSecure();}
    void launchDeviceCredential(){try{KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);if(Build.VERSION.SDK_INT>=21&&km!=null&&km.isDeviceSecure()){Intent i=km.createConfirmDeviceCredentialIntent("Parental-Link","Unlock parent dashboard");if(i!=null)startActivityForResult(i,AUTH_REQUEST);}}catch(Exception e){toast("Biometric unlock unavailable");}}
    void unlockParentApp(String method){SharedPreferences.Editor e=getSharedPreferences("p",0).edit();e.putInt("pinFailCount",0).putLong("pinLockUntil",0).apply();unlockedThisRun=true;addLog("Parent app unlocked by "+method);showConnectedParent(false);}    
    void registerWrongPinAttempt(){SharedPreferences p=getSharedPreferences("p",0);int fails=p.getInt("pinFailCount",0)+1;long[] delays={5000L,30000L,60000L,900000L,3600000L};long d=delays[Math.min(fails-1,delays.length-1)];p.edit().putInt("pinFailCount",fails).putLong("pinLockUntil",System.currentTimeMillis()+d).apply();addLog("Wrong parent PIN attempt");toast("Wrong PIN");showParentAppLock();}
    void showCreateParentPin(SharedPreferences p){root.addView(tv("Create a 4–6 digit parent PIN fallback.",15));EditText p1=new EditText(this);p1.setHint("New PIN");p1.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);p1.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});root.addView(p1);EditText p2=new EditText(this);p2.setHint("Repeat PIN");p2.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);p2.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});root.addView(p2);Button save=btn("Save PIN and unlock");root.addView(save);if(canUseDeviceCredential()){Button bio=btn("Unlock with biometrics");root.addView(bio);bio.setOnClickListener(v->launchDeviceCredential());}save.setOnClickListener(v->{String a=p1.getText().toString().trim(),b=p2.getText().toString().trim();if(a.length()<4||a.length()>6){toast("Use 4 to 6 digits");return;}if(!a.equals(b)){toast("PINs do not match");return;}p.edit().putString("appPin",a).putInt("pinFailCount",0).putLong("pinLockUntil",0).apply();unlockParentApp("new PIN");});}

    void showUserMenu(){if(sidePanel!=null&&sidePanel.isShowing()){sidePanel.dismiss();return;}LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(32,48,32,32);panel.setBackgroundColor(Color.rgb(220,238,248));TextView title=tv("Parent Control",22);panel.addView(title);String[] items={"Devices","Blocked apps","Logs","Troubleshooting","Version & updates","Profiles","Second parent","Unlock codes","Settings","Add device","Exit parent monitor"};for(String item:items){Button b=btn(item);panel.addView(b);b.setOnClickListener(v->{if(sidePanel!=null)sidePanel.dismiss();if(item.equals("Logs"))showLogsScreen();else if(item.equals("Troubleshooting"))showTroubleshootingScreen();else if(item.equals("Version & updates"))showVersionScreen();else if(item.equals("Devices"))showDevicesScreen();else if(item.equals("Add device"))showParentConnection("");else if(item.equals("Blocked apps"))showBlockedAppsScreen();else if(item.equals("Profiles"))showProfilesScreen();else if(item.equals("Second parent"))showSecondParentScreen();else if(item.equals("Unlock codes"))showUnlockCodesScreen();else if(item.equals("Settings"))showSettingsScreen();else if(item.equals("Exit parent monitor")){stopService(new Intent(this,ParentMonitorService.class));addLog("Parent monitor stopped");toast("Parent monitor stopped");}else toast(item+" will be added later");});}TextView version=tv("Parental-Link v"+APP_VERSION,12);panel.addView(version);int w=(int)(getResources().getDisplayMetrics().widthPixels*0.84f);sidePanel=new PopupWindow(panel,w,ViewGroup.LayoutParams.MATCH_PARENT,true);sidePanel.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.rgb(220,238,248)));sidePanel.setOutsideTouchable(true);sidePanel.showAtLocation(root,Gravity.RIGHT|Gravity.TOP,0,0);}
    void showDevicesScreen(){base("Devices");currentScreen="devices";DeviceProfile deviceProfile=new DeviceProfile(this);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView d=tv(deviceProfile.childIcon()+" "+deviceProfile.childNickname()+"\n"+deviceProfile.childIp(),17);Button edit=btn("✎");row.addView(d,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));row.addView(edit);root.addView(row);edit.setOnClickListener(v->askDeviceDetails(false));root.addView(tv("Edit opens nickname, device type and the child device master password.",13));Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,80));Button add=btn("＋ Add device");LinearLayout addRow=new LinearLayout(this);addRow.setGravity(Gravity.RIGHT);addRow.addView(add);root.addView(addRow);add.setOnClickListener(v->showParentConnection(""));}
    void showProfilesScreen(){base("Profiles");currentScreen="profiles";root.addView(tv("Profiles send a group of rules to the child tablet. Full scheduled rules can be added later.",15));Button homework=btn("Homework mode");Button bedtime=btn("Bedtime mode");Button free=btn("Free time");root.addView(homework);root.addView(bedtime);root.addView(free);homework.setOnClickListener(v->cmd("profile","homework"));bedtime.setOnClickListener(v->cmd("profile","bedtime"));free.setOnClickListener(v->cmd("profile","free_time"));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void showSecondParentScreen(){base("Second parent");currentScreen="second_parent";root.addView(tv("Second-parent approval groundwork. A second parent should be approved by the first parent before the child accepts the new device.",15));root.addView(tv("Current parent identity: "+getSharedPreferences("p",0).getString("parentName","Parent Control")+"\nDevice ID: "+getSharedPreferences("p",0).getString("localDeviceId",""),14));Button request=btn("Create approval request scaffold");root.addView(request);request.setOnClickListener(v->{getSharedPreferences("p",0).edit().putBoolean("securityAttention",true).apply();addLog("Second parent approval request created");toast("Approval request scaffold created");});Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}

    void showLogsScreen(){base("Logs");currentScreen="logs";SharedPreferences p=getSharedPreferences("p",0);LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);Button one=btn("One line");Button full=btn("Full status");Button clear=btn("Clear logs");controls.addView(one,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));controls.addView(full,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));controls.addView(clear,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(controls);LinearLayout filters=new LinearLayout(this);filters.setOrientation(LinearLayout.HORIZONTAL);final String[] currentFilter={"All"};String[] fs={"All","Activity","Security","Connection","Commands","Debug"};for(String f:fs){Button fb=btn(f);filters.addView(fb);fb.setOnClickListener(v->{currentFilter[0]=((Button)v).getText().toString();renderLogsList(p.getString("logs",""),currentFilter[0],false);});}root.addView(filters);one.setOnClickListener(v->renderLogsList(p.getString("logs",""),currentFilter[0],false));full.setOnClickListener(v->renderLogsList(p.getString("logs",""),currentFilter[0],true));clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear logs?").setMessage("This will remove the event history from this device.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{getSharedPreferences("p",0).edit().remove("logs").remove("latestLog").apply();showLogsScreen();}).show());renderLogsList(p.getString("logs",""),"All",false);} 
    void renderLogsList(String raw,String filter,boolean full){while(root.getChildCount()>4)root.removeViewAt(4);if(raw==null||raw.trim().length()==0){root.addView(tv("No logs yet",15));return;}String[] lines=raw.split("\n");for(String line:lines){if(line.trim().length()==0)continue;if(!"All".equals(filter)&&!line.contains("["+filter+"/"))continue;TextView row=tv(full?AppLog.detail(line):AppLog.lineSummary(line),14);row.setSingleLine(!full);row.setEllipsize(TextUtils.TruncateAt.END);row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Log details").setMessage(AppLog.detail(line)).setPositiveButton("OK",null).show());root.addView(row);} }

    void showTroubleshootingScreen(){base("Troubleshooting");currentScreen="troubleshooting";SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Connection diagnostics",18));root.addView(tv("Parent",16));root.addView(tv("Local IP: "+getIp()+"\nChild IP: "+(childIp.length()>0?childIp:"unknown")+"\nProtocol: "+PROTOCOL_VERSION+" / minimum supported: "+MIN_PROTOCOL,14));long last=p.getLong("lastStatusMs",0);String lastText=last>0?((System.currentTimeMillis()-last)/60000)+" min ago":"never";root.addView(tv("Child",16));root.addView(tv("Last status: "+lastText+"\nVersion: "+p.getString("remoteVersion","unknown")+"\nProtocol: "+p.getString("remoteProtocol","unknown")+"\nPermissions: "+p.getString("remotePermissions","unknown")+"\nDND: "+p.getString("remoteDnd","unknown")+"\nCurrent app: "+currentAppDisplay(),14));root.addView(tv("Actions",18));Button refresh=btn("Refresh diagnostics");Button logs=btn("Open logs");Button export=btn("Export logs");Button restartParent=btn("Restart parent monitor");root.addView(refresh);root.addView(logs);root.addView(export);root.addView(restartParent);refresh.setOnClickListener(v->{cmdWithCallback("usage","today",resp->{updateUsageViews(resp,tv("",1),null);addLog("Connection","Info","Diagnostics refreshed",resp);showTroubleshootingScreen();},err->{addLog("Connection","Error","Diagnostics refresh failed",err);out(err);});});logs.setOnClickListener(v->showLogsScreen());export.setOnClickListener(v->{String data=getSharedPreferences("p",0).getString("logs","");Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_SUBJECT,"Parental-Link logs");send.putExtra(Intent.EXTRA_TEXT,data.length()>0?data:"No logs");startActivity(Intent.createChooser(send,"Export logs"));});restartParent.setOnClickListener(v->{stopService(new Intent(this,ParentMonitorService.class));startService(new Intent(this,ParentMonitorService.class));addLog("Connection","Info","Parent monitor restarted","Restarted from troubleshooting");toast("Parent monitor restarted");});}

    void showVersionScreen(){base("Version & updates");currentScreen="updates";SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Current version: "+APP_VERSION,16));root.addView(tv("Protocol: "+PROTOCOL_VERSION+" / minimum supported: "+MIN_PROTOCOL,16));String remote=p.getString("remoteVersion","");String remoteProtocol=p.getString("remoteProtocol","");root.addView(tv(remote.length()>0?"Child version: "+remote+(remoteProtocol.length()>0?" / protocol "+remoteProtocol:""):"Child version: unknown until next successful command",16));String latest=p.getString("latestVersion","");TextView status=tv(latest.length()>0?"Latest GitHub release: "+latest:"Latest GitHub release: not checked",16);root.addView(status);root.addView(tv("Repository: "+DEFAULT_REPO,14));Button check=btn("Check for updates");Button open=btn("Open latest release");Button prompt=btn("Send update prompt to tablet");root.addView(check);root.addView(open);root.addView(prompt);check.setOnClickListener(v->checkLatestRelease(DEFAULT_REPO,status));open.setOnClickListener(v->{String url=getSharedPreferences("p",0).getString("latestReleaseUrl","");if(url.length()==0)toast("Check for updates first");else startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));});prompt.setOnClickListener(v->{String latestForPrompt=getSharedPreferences("p",0).getString("latestVersion","");cmd("update_prompt",latestForPrompt.length()>0?latestForPrompt:"new version");});root.addView(tv("Tablet updates should be initiated by the parent. Update source is fixed for safety.",14));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void checkLatestRelease(String repo,TextView status){UpdateChecker.checkLatestRelease(this,repo,status);}
    void addLog(String msg){AppLog.add(this,msg);} void addLog(String category,String severity,String summary,String details){AppLog.add(this,category,severity,summary,details);} 
    boolean childPermissionsNeedAttention(){String perms=getSharedPreferences("p",0).getString("remotePermissions","");return perms.length()>0&&(!perms.contains("admin=true")||!perms.contains("usage=true")||!perms.contains("accessibility=true")||!perms.contains("notifications=true"));}
    String dashboardStatusCircle(){SharedPreferences p=getSharedPreferences("p",0);if(childPermissionsNeedAttention())return "🔴";long last=p.getLong("lastStatusMs",0);if(last==0)return "⚫";long age=System.currentTimeMillis()-last;return age>10L*60L*1000L?"🟡":"🟢";}
    String permissionStatusText(){String perms=getSharedPreferences("p",0).getString("remotePermissions","");if(perms.length()==0)return "Permission status: unknown";if(childPermissionsNeedAttention())return "🔴 Permissions needed on child tablet";return "🟢 Required permissions OK";}
    boolean childUsageAccessOk(){String perms=getSharedPreferences("p",0).getString("remotePermissions","");return perms.length()==0||perms.contains("usage=true");}
    String currentAppDisplay(){if(!childUsageAccessOk())return "Unavailable";return cleanAppName(getSharedPreferences("p",0).getString("lastCurrentApp","--"));}
    String cleanAppName(String raw){if(raw==null)return "--";String v=raw.trim();if(v.length()==0)return "--";int paren=v.indexOf("(");if(paren>0)v=v.substring(0,paren).trim();if(v.startsWith("package:"))v=v.substring(8);if(v.matches("[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)+")){int dot=v.lastIndexOf('.');if(dot>=0&&dot<v.length()-1)v=v.substring(dot+1);}return v.length()>0?v:"--";}
    void showCurrentAppActions(TextView currentAppView){String app=currentAppDisplay();String[] items={"Block current app","Timeout current app","View usage"};new AlertDialog.Builder(this).setTitle("Current app: "+app).setItems(items,(d,which)->{if(app.equals("Unavailable")||app.equals("--")){toast("Current app unavailable");return;}if(which==0){cmdWithCallback("block_current","",resp->{addLog("Commands","Info","Current app blocked",resp);out(resp);},err->{addLog("Commands","Error","Block current app failed",err);out(err);});}else if(which==1){askCurrentAppTimeout(app);}else{cmdWithCallback("usage","today",resp->{String summary=usageSummary(resp);addLog("Activity","Info","Usage requested",summary);out(summary);},err->{out(err);});}}).show();}
    void askCurrentAppTimeout(String appLabel){final String[] labels={"5 min","10 min","15 min","30 min","1 h","2 h"};final int[] mins={5,10,15,30,60,120};new AlertDialog.Builder(this).setTitle("Timeout current app").setMessage(appLabel).setItems(labels,(d,which)->{cmd("timeout_current_app",String.valueOf(mins[which]));addLog("Commands","Info","Current app timeout requested",appLabel+" for "+labels[which]);}).show();}
    void askAppTimeout(String pkg,String label){final String[] labels={"5 min","10 min","15 min","30 min","1 h","2 h","Until tomorrow"};final int[] mins={5,10,15,30,60,120,1440};new AlertDialog.Builder(this).setTitle("Timeout app").setMessage(label).setItems(labels,(d,which)->{cmd("timeout_app",pkg+"|"+mins[which]);addLog("Commands","Info","App timeout requested",label+" for "+labels[which]);}).show();}


    void showStart(){base("");TextView title=tv("Set up this device",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView subtitle=tv("Choose how this device will be used.",15);subtitle.setGravity(Gravity.CENTER);root.addView(subtitle);Button p=btn("Parent phone");Button c=btn("Child tablet");root.addView(p);root.addView(c);TextView note=tv("You can change this later by clearing app data.",13);note.setGravity(Gravity.CENTER);root.addView(note);p.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection("");});c.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","child").apply();showChild();});}


    void showChild(){key=getOrCreateKey();base("");SharedPreferences p=getSharedPreferences("p",0);boolean connected=p.getBoolean("childConnected",false)||p.getString("parentPassword","").length()>0;String parentName=p.getString("parentName","Parent Control");if(parentName==null||parentName.trim().length()==0)parentName="Parent Control";final String parentLabel=parentName;ChildHomeScreen.PairViews pair=ChildHomeScreen.render(this,root,connected,childPairingDetailsVisible,parentLabel,childLocalPermissionsOk(),v->startChildService(),v->askChildSettingsUnlock(),v->{childPairingDetailsVisible=!childPairingDetailsVisible;showChild();},v->{startActivity(new Intent(this, com.enigma.familylinklite.audio.ChildAudioMessageActivity.class));},v->{Intent ci=new Intent(this, com.enigma.familylinklite.calls.CallActivity.class);ci.putExtra("mode","outgoing");ci.putExtra("parent",parentLabel);startActivity(ci);});childPairCodeView=pair.code;childCountdownView=pair.countdown;childQrView=pair.qr;root.addView(log);listenLogs();startChildService();if(childPairCodeView!=null)updateChildPairUi();}

    void updateChildPairUi(){if(childPairCodeView==null)return;String code=currentPairCode(key);long remain=120-(System.currentTimeMillis()/1000%120);String formatted=code.substring(0,3)+"-"+code.substring(3);childPairCodeView.setText(formatted);childCountdownView.setText(String.format(Locale.US,"New code in %02d:%02d",remain/60,remain%60));String deep="family-link://pair?code="+code;childQrView.setImageBitmap(qrBitmap(deep,260));handler.postDelayed(this::updateChildPairUi,1000);}
    void startChildService(){getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(key)).apply();Intent i=new Intent(this,ChildServerService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);out("Child background server start requested");}

    void showParentConnection(String prefill){base("");currentScreen="pairing";TextView title=tv("Connect tablet",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=tv("Enter the 6-digit code shown on the child tablet.",15);sub.setGravity(Gravity.CENTER);root.addView(sub);LinearLayout boxes=new LinearLayout(this);boxes.setOrientation(LinearLayout.HORIZONTAL);boxes.setGravity(Gravity.CENTER);EditText[] digits=new EditText[6];String clean=prefill==null?"":prefill.replaceAll("\\D","");for(int i=0;i<6;i++){final int idx=i;EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);e.setTextSize(24);e.setSingleLine(true);e.setSelectAllOnFocus(true);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(1)});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(72,72);lp.setMargins(6,6,6,6);boxes.addView(e,lp);digits[i]=e;if(i<clean.length())e.setText(String.valueOf(clean.charAt(i)));e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence cs,int st,int before,int count){if(cs.length()==1&&idx<5)digits[idx+1].requestFocus();}public void afterTextChanged(Editable ed){}});e.setOnKeyListener((v,k,ev)->{if(k==KeyEvent.KEYCODE_DEL&&ev.getAction()==KeyEvent.ACTION_DOWN&&((EditText)v).getText().length()==0&&idx>0){digits[idx-1].setText("");digits[idx-1].requestFocus();return true;}return false;});}
        root.addView(boxes);Button connect=btn("Connect");Button scan=btn("Scan QR");root.addView(connect);root.addView(scan);TextView small=tv("The app searches the current Wi-Fi automatically.",13);small.setGravity(Gravity.CENTER);root.addView(small);Button advanced=btn("Advanced manual pairing");root.addView(advanced);connect.setOnClickListener(v->{StringBuilder sb=new StringBuilder();for(EditText e:digits)sb.append(e.getText().toString().replaceAll("\\D", ""));String c=sb.toString();if(c.length()!=6){toast("Enter 6 digits");return;}pairByScanningSubnet(c);});scan.setOnClickListener(v->{requestPermissions(new String[]{Manifest.permission.CAMERA},8);try{IntentIntegrator integrator=new IntentIntegrator(this);integrator.setPrompt("Scan the QR shown on the child tablet");integrator.setBeepEnabled(false);integrator.setOrientationLocked(false);integrator.initiateScan();}catch(Exception e){toast("Camera scanner failed. Use the code manually.");addLog("QR scanner failed");}});advanced.setOnClickListener(v->{LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText full=edit("ip:45454:pairingSecret");box.addView(full);new AlertDialog.Builder(this).setTitle("Advanced manual pairing").setMessage("Use only if automatic pairing fails.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Connect",(d,w)->{try{String[] p=full.getText().toString().trim().split(":");saveConnection(p[0],p[2]);}catch(Exception e){toast("Invalid full pairing code");}}).show();});root.addView(log);}

    void handlePairQr(String text){try{if(text.startsWith("family-link://")){Uri u=Uri.parse(text);String c=u.getQueryParameter("code");if(c!=null){showParentConnection(c);pairByScanningSubnet(c.replaceAll("\\D", ""));return;}}String c=text.replaceAll("\\D","");if(c.length()==6){showParentConnection(c);pairByScanningSubnet(c);return;}toast("Invalid QR code");}catch(Exception e){toast("Invalid QR code");}}
    void pairByScanningSubnet(String code){out("Searching this Wi-Fi for child tablet...");String myIp=getIp();String[] p=myIp.split("\\.");if(p.length!=4){toast("Cannot detect Wi-Fi IP");return;}String prefix=p[0]+"."+p[1]+"."+p[2]+".";AtomicBoolean done=new AtomicBoolean(false);ExecutorService ex=Executors.newFixedThreadPool(32);CountDownLatch latch=new CountDownLatch(254);String parentId=getSharedPreferences("p",0).getString("localDeviceId",UUID.randomUUID().toString());for(int i=1;i<=254;i++){final String ip=prefix+i;ex.submit(()->{try{if(done.get()||ip.equals(myIp))return;Socket s=new Socket();s.connect(new InetSocketAddress(ip,PORT),350);s.setSoTimeout(800);PrintWriter w=new PrintWriter(s.getOutputStream(),true);w.println("PAIR|"+code+"|"+parentId+"|"+PROTOCOL_VERSION+"|"+MIN_PROTOCOL);BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String resp=r.readLine();s.close();if(resp!=null&&resp.startsWith("OK|")&&done.compareAndSet(false,true)){String[] parts=resp.split("\\|");runOnUiThread(()->{saveConnection(ip,parts[1]);getSharedPreferences("p",0).edit().putString("remoteVersion",parts.length>3?parts[3]:"unknown").apply();askDeviceDetails(true);});}}catch(Exception ignored){}finally{latch.countDown();}});}new Thread(()->{try{latch.await(12,TimeUnit.SECONDS);}catch(Exception ignored){}ex.shutdownNow();if(!done.get())runOnUiThread(()->{toast("No tablet found for that code");out("Pairing failed. Check same Wi-Fi and child server notification.");});}).start();}
    void saveConnection(String ip,String secret){try{byte[] decoded=Base64.getDecoder().decode(secret);childIp=ip;key=decoded;new SavedConnection(this).saveParentConnection(childIp,secret);addLog("Connection saved");toast("Connection saved");showConnectedParent(true);}catch(Exception e){toast("Invalid pairing secret");out("Invalid pairing secret: "+e.getMessage());}}
    void askDeviceDetails(boolean firstTime){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText name=oneLine("Device nickname");name.setText(getSharedPreferences("p",0).getString("childNickname","Child tablet"));EditText parentName=oneLine("Parent name");parentName.setText(getSharedPreferences("p",0).getString("parentName","Parent Control"));EditText pass=oneLine("Parent password, 4-6 digits");pass.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);pass.setText(getSharedPreferences("p",0).getString("parentPassword",""));box.addView(name);if(firstTime){box.addView(parentName);box.addView(pass);}else{TextView mpStatus=tv(getSharedPreferences("p",0).getString("parentPassword","").length()>0?"Child device master password: saved":"Child device master password: not set",14);Button mpEdit=btn(getSharedPreferences("p",0).getString("parentPassword","").length()>0?"Edit master password":"Add master password");box.addView(mpStatus);box.addView(mpEdit);mpEdit.setOnClickListener(v->askEditChildMasterPassword(mpStatus));}String[] icons={"📟 Tablet","📱 Phone","💻 PC"};new AlertDialog.Builder(this).setTitle(firstTime?"Name this device":"Edit device").setView(box).setSingleChoiceItems(icons,0,(d,which)->{String icon=icons[which].substring(0,2).trim();getSharedPreferences("p",0).edit().putString("childIcon",icon).apply();}).setPositiveButton("Save",(d,w)->{String n=name.getText().toString().trim();if(n.length()==0)n="Child tablet";SharedPreferences.Editor ed=getSharedPreferences("p",0).edit().putString("childNickname",n);if(firstTime){String pn=parentName.getText().toString().trim();if(pn.length()==0)pn="Parent Control";String pw=pass.getText().toString().trim();if(pw.length()<4||pw.length()>6){toast("Use a 4 to 6 digit parent password");return;}ed.putString("parentName",pn).putString("parentPassword",pw);}ed.apply();if(firstTime){cmd("set_parent_password",getSharedPreferences("p",0).getString("parentName","Parent Control")+"|"+getSharedPreferences("p",0).getString("parentPassword",""));}showConnectedParent(true);}).setNegativeButton("Later",null).show();}

    void askEditChildMasterPassword(TextView status){if(!unlockedThisRun){toast("Unlock the parent app first");return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText p1=oneLine("New child master password, 4-6 digits");p1.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);p1.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});EditText p2=oneLine("Repeat password");p2.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);p2.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});box.addView(tv("This password unlocks the child settings locally. Do not store it in logs.",13));box.addView(p1);box.addView(p2);new AlertDialog.Builder(this).setTitle("Child device master password").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String a=p1.getText().toString().trim();String b=p2.getText().toString().trim();if(a.length()<4||a.length()>6){toast("Use 4 to 6 digits");return;}if(!a.equals(b)){toast("Passwords do not match");return;}getSharedPreferences("p",0).edit().putString("parentPassword",a).apply();cmdWithCallback("set_parent_password",getSharedPreferences("p",0).getString("parentName","Parent Control")+"|"+a,ok->{if(status!=null)status.setText("Child device master password: saved");addLog("Security","Info","Child master password updated","Password value was not logged");toast("Master password updated");},err->{addLog("Security","Error","Child master password update failed",err);out(err);});}).show();}


    void askChildSettingsUnlock(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText code=oneLine("Parent password or one-time code");code.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);box.addView(code);new AlertDialog.Builder(this).setTitle("Unlock settings").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Unlock",(d,w)->{String entered=code.getText().toString().trim();SharedPreferences p=getSharedPreferences("p",0);String master=p.getString("parentPassword","");String otp=p.getString("childOtp","");if(master.length()>0&&entered.equals(master)){p.edit().putString("lastUnlockMethod","device master password").apply();showChildSettings("device master password");return;}if(otp.length()>0&&entered.equals(otp)){String who=p.getString("childOtpParent","Parent Control");p.edit().remove("childOtp").putString("lastUnlockMethod",who+" one-time password").apply();addLog("Child settings unlocked by "+who+" one-time password");showChildSettings(who+" one-time password");return;}toast("Wrong password");addLog("Wrong child settings unlock attempt");}).show();}

    boolean childLocalPermissionsOk(){return isDeviceAdminActive()&&hasUsageAccess()&&isAccessibilityEnabled()&&(Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)&&Settings.canDrawOverlays(this);}
    boolean hasNotificationPolicyAccess(){try{NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);return nm!=null&&nm.isNotificationPolicyAccessGranted();}catch(Exception e){return false;}}
    void showChildSettings(String method){base("Child settings");currentScreen="child_settings";root.addView(tv("Unlocked with: "+method,14));root.addView(tv("Connection information",18));root.addView(tv("Parent: "+getSharedPreferences("p",0).getString("parentName","Parent Control")+"\nDevice ID: "+getSharedPreferences("p",0).getString("localDeviceId","unknown")+"\nIP: "+getIp()+"\nServer: running",14));root.addView(tv(childLocalPermissionsOk()?"🟢 Required access OK":"🔴 New permissions needed",16));root.addView(tv("Required access",18));addPermissionRow("Device Administrator",isDeviceAdminActive(),v->startActivity(new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN).putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,new ComponentName(this,AdminReceiver.class))));addPermissionRow("Usage Access",hasUsageAccess(),v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));addPermissionRow("Accessibility Service",isAccessibilityEnabled(),v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));addPermissionRow("Notifications",Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED,v->{if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);});addPermissionRow("Display over other apps",Settings.canDrawOverlays(this),v->startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()))));addPermissionRow("DND / Notification Policy Access",hasNotificationPolicyAccess(),v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS)));addPermissionRow("Battery unrestricted",false,v->startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS)));Button check=btn("Check again");Button restart=btn("Restart server");Button travel=btn("Remove all limitations / Travel mode");Button remove=btn("Remove parental control");root.addView(check);root.addView(restart);root.addView(travel);root.addView(remove);check.setOnClickListener(v->showChildSettings(method));restart.setOnClickListener(v->startChildService());travel.setOnClickListener(v->confirmChildTravelMode(method));remove.setOnClickListener(v->confirmRemoveApp(method));root.addView(log);listenLogs();}
    void addPermissionRow(String name,boolean ok,View.OnClickListener action){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView t=tv((ok?"✅ ":"⚠ ")+name,15);row.addView(t,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));if(!ok){Button b=btn("Enable");b.setOnClickListener(action);row.addView(b);}root.addView(row);}

    void confirmChildTravelMode(String method){new AlertDialog.Builder(this).setTitle("Remove all limitations?").setMessage("This is local Travel mode. It clears active Disable Use, Timeout, blocked apps and profiles on this child device. Authorised by: "+method).setNegativeButton("Cancel",null).setPositiveButton("Remove limitations",(d,w)->{removeAllLocalLimitations(method);showChildSettings(method);}).show();}
    void removeAllLocalLimitations(String method){SharedPreferences prefs=getSharedPreferences("rules",0);SharedPreferences.Editor ed=prefs.edit();for(String k:prefs.getAll().keySet()){if(k.startsWith("blocked_until_"))ed.remove(k);}ed.remove("lock_until").remove("lock_mode").remove("active_profile").remove("profile_until").apply();sendBroadcast(new Intent("com.enigma.familylinklite.CLOSE_ATTENTION"));addLog("Security","Info","Travel mode enabled","All local limitations removed by "+method);toast("All limitations removed");}

    boolean isDeviceAdminActive(){try{DevicePolicyManager dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);return dpm!=null&&dpm.isAdminActive(new ComponentName(this,AdminReceiver.class));}catch(Exception e){return false;}}
    boolean hasUsageAccess(){try{AppOpsManager a=(AppOpsManager)getSystemService(APP_OPS_SERVICE);int mode=a.checkOpNoThrow(AppOpsManager.OPSTR_GET_USAGE_STATS,android.os.Process.myUid(),getPackageName());return mode==AppOpsManager.MODE_ALLOWED;}catch(Exception e){return false;}}
    boolean isAccessibilityEnabled(){try{String enabled=Settings.Secure.getString(getContentResolver(),Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES);return enabled!=null&&enabled.toLowerCase(Locale.US).contains(getPackageName().toLowerCase(Locale.US));}catch(Exception e){return false;}}
    void confirmRemoveApp(String method){new AlertDialog.Builder(this).setTitle("Remove Parental-Link?").setMessage("This will disable protection features and start uninstall. Authorised by: "+method).setNegativeButton("Cancel",null).setPositiveButton("Continue",(d,w)->{addLog("Child app removal started. Authorised by: "+method);try{DevicePolicyManager dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName admin=new ComponentName(this,AdminReceiver.class);if(dpm!=null&&dpm.isAdminActive(admin))dpm.removeActiveAdmin(admin);}catch(Exception e){out("Could not disable admin automatically: "+e.getMessage());}try{startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Exception ignored){}try{Intent del=new Intent(Intent.ACTION_DELETE,Uri.parse("package:"+getPackageName()));startActivity(del);}catch(Exception e){out("Open Android app settings to uninstall: "+e.getMessage());}}).show();}
    void showSettingsScreen(){base("Settings");currentScreen="settings";root.addView(tv("Appearance",18));root.addView(tv("Theme",15));RadioGroup theme=new RadioGroup(this);theme.setOrientation(RadioGroup.VERTICAL);String currentTheme=getSharedPreferences("p",0).getString("themeMode","system");String[] labels={"Follow device","Light","Dark"};String[] values={"system","light","dark"};for(int i=0;i<labels.length;i++){RadioButton rb=new RadioButton(this);rb.setText(labels[i]);rb.setTag(values[i]);rb.setChecked(values[i].equals(currentTheme));theme.addView(rb);}theme.setOnCheckedChangeListener((g,id)->{RadioButton rb=g.findViewById(id);if(rb!=null){getSharedPreferences("p",0).edit().putString("themeMode",String.valueOf(rb.getTag())).apply();toast("Theme saved");}});root.addView(theme);root.addView(tv("Security",18));Button remove=btn("Remove parental control");root.addView(remove);remove.setOnClickListener(v->confirmRemoveParentalControl());root.addView(tv("This removes only Parental-Link settings on this device. It does not reset the phone, tablet, or TV.",13));}

    void confirmRemoveParentalControl(){SharedPreferences p=getSharedPreferences("p",0);String otherParent=p.getString("otherParentName","");String devices=childDeviceListText();StringBuilder msg=new StringBuilder();msg.append("This does not reset the device,\n");msg.append("it only removes the settings of the Parental-Link application on your device.\n\n");if(otherParent.length()>0){msg.append("The Parental-Link application of ").append(otherParent).append(" will continue to control the following devices:\n").append(devices);}else{msg.append("The Parental-Link application will delete its settings and a new first-time connection will be available for the following devices:\n").append(devices);}AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Remove parental control?").setMessage(msg.toString()).setNegativeButton("Cancel",null).setPositiveButton("Remove in 5",null).create();dlg.setOnShowListener(di->{Button b=dlg.getButton(AlertDialog.BUTTON_POSITIVE);b.setEnabled(false);final int[] remaining={5};Runnable tick=new Runnable(){public void run(){if(!dlg.isShowing())return;if(remaining[0]>0){b.setText("Remove in "+remaining[0]);remaining[0]--;handler.postDelayed(this,1000);}else{b.setText("Remove");b.setEnabled(true);}}};tick.run();b.setOnClickListener(v->{dlg.dismiss();resetLocalParentalLinkData();});});dlg.show();}

    String childDeviceListText(){SharedPreferences p=getSharedPreferences("p",0);String nickname=p.getString("childNickname","Child device");String ip=p.getString("childIp","");String line="• "+nickname+(ip.length()>0?" ("+ip+")":"");return line+"\n";}

    void resetLocalParentalLinkData(){try{stopService(new Intent(this,ParentMonitorService.class));}catch(Exception ignored){}getSharedPreferences("p",0).edit().clear().apply();unlockedThisRun=false;authPromptLaunched=false;childIp="";key=null;toast("Parental-Link settings removed");showStart();}
    void showUnlockCodesScreen(){base("Unlock codes");currentScreen="unlock_codes";TextView current=tv("No active one-time code",22);current.setGravity(Gravity.CENTER);root.addView(tv("Generate a one-time code for unlocking child settings. The code is invalidated after first use on the tablet.",15));root.addView(current);Button gen=btn("Generate one-time code");root.addView(gen);gen.setOnClickListener(v->{String who=getSharedPreferences("p",0).getString("parentName","Parent Control");cmdWithCallback("otp_generate",who,resp->{String code=resp.replace("OTP:","").trim();current.setText(code.length()>0?code:"No code returned");addLog("One-time unlock code generated");},err->{current.setText("Failed to generate code");out(err);});});root.addView(log);}
    void showBlockedAppsScreen(){base("Blocked apps");currentScreen="blocked_apps";root.addView(tv("Blocked apps are listed below. Press Remove to unblock one app, or Add app to choose from the child tablet apps.",14));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button add=btn("Add app");Button refresh=btn("Refresh");actions.addView(add,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));actions.addView(refresh,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(actions);add.setOnClickListener(v->showAddBlockedAppDialog(list));refresh.setOnClickListener(v->loadBlockedAppsList(list));refresh.performClick();root.addView(log);}
    void showConnectedParent(boolean tryNow){fixedBase("");currentScreen="dashboard";try{if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,ParentMonitorService.class));else startService(new Intent(this,ParentMonitorService.class));}catch(Exception ignored){}SharedPreferences p=getSharedPreferences("p",0);String nick=p.getString("childNickname","Child tablet");String icon=p.getString("childIcon","📟");boolean disableActive=p.getBoolean("disableUseActive",false);boolean timeoutActive=p.getBoolean("timeoutActive",false);
        LinearLayout deviceRow=new LinearLayout(this);deviceRow.setOrientation(LinearLayout.HORIZONTAL);Button prev=btn("‹");Button next=btn("›");TextView device=tv(icon+" "+nick,20);deviceRow.addView(prev);deviceRow.addView(device,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));deviceRow.addView(next);root.addView(deviceRow);prev.setOnClickListener(v->toast("No previous saved device"));next.setOnClickListener(v->toast("No next saved device"));
        LinearLayout statusRow=new LinearLayout(this);statusRow.setOrientation(LinearLayout.HORIZONTAL);TextView status=tv(dashboardStatusCircle()+" Disconnected",16);Button refresh=btn("↻");refresh.setTextSize(26);statusRow.addView(status,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));statusRow.addView(refresh);root.addView(statusRow);TextView healthDetails=tv("Version status: unknown\n"+permissionStatusText(),13);root.addView(healthDetails);
        LinearLayout summary=new LinearLayout(this);summary.setOrientation(LinearLayout.HORIZONTAL);TextView screen=tv("Today\n--:--",22);screen.setGravity(Gravity.CENTER);TextView currentApp=tv("Current app ›\n"+currentAppDisplay(),18);currentApp.setGravity(Gravity.CENTER);currentApp.setOnClickListener(v->showCurrentAppActions(currentApp));summary.addView(screen,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));summary.addView(currentApp,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(summary);
        TextView blocked=tv("Blocked apps: --    View ›",15);blocked.setGravity(Gravity.CENTER);blocked.setOnClickListener(v->showBlockedAppsScreen());root.addView(blocked);
        TextView lastUpdate=tv("Last update: --",13);root.addView(lastUpdate);
        LinearLayout volHeader=new LinearLayout(this);volHeader.setOrientation(LinearLayout.HORIZONTAL);TextView volTitle=tv("Volume",18);TextView dnd=tv("DND: "+getSharedPreferences("p",0).getString("remoteDnd","unknown"),13);Button dndPing=btn("Allow ping");Button mute=btn("🔇");volHeader.addView(volTitle,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));volHeader.addView(dnd);volHeader.addView(dndPing);volHeader.addView(mute);root.addView(volHeader);
        LinearLayout streams=new LinearLayout(this);streams.setOrientation(LinearLayout.HORIZONTAL);final String[] selectedStream={"media"};String[] streamLabels={"Media","Calls","Notifications","System"};for(String sl:streamLabels){Button b=btn(sl);streams.addView(b);b.setOnClickListener(v->{selectedStream[0]=((Button)v).getText().toString().toLowerCase(Locale.US);});}root.addView(streams);
        LinearLayout volRow=new LinearLayout(this);volRow.setOrientation(LinearLayout.HORIZONTAL);Button minus=btn("−");Button plus=btn("+");SeekBar volumeBar=new SeekBar(this);volumeBar.setMax(100);volumeBar.setProgress(parentVolume);volRow.addView(minus);volRow.addView(volumeBar,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));volRow.addView(plus);root.addView(volRow);TextView volLabel=tv("Maximum allowed: "+parentVolume+"%",14);root.addView(volLabel);
        volumeBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int progress,boolean fromUser){if(fromUser){parentVolume=progress;volLabel.setText("Maximum allowed: "+parentVolume+"%");}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){cmd("volume",selectedStream[0]+"|"+parentVolume+"|max");}});minus.setOnClickListener(v->{parentVolume=Math.max(0,parentVolume-1);volumeBar.setProgress(parentVolume);volLabel.setText("Maximum allowed: "+parentVolume+"%");cmd("volume",selectedStream[0]+"|"+parentVolume+"|max");});plus.setOnClickListener(v->{parentVolume=Math.min(100,parentVolume+1);volumeBar.setProgress(parentVolume);volLabel.setText("Maximum allowed: "+parentVolume+"%");cmd("volume",selectedStream[0]+"|"+parentVolume+"|max");});mute.setOnClickListener(v->{SharedPreferences sp=getSharedPreferences("p",0);String key="remote_muted_"+selectedStream[0];boolean muted=sp.getBoolean(key,false);if(muted){cmd("volume",selectedStream[0]+"|0|unmute");sp.edit().putBoolean(key,false).apply();mute.setText("🔇");volLabel.setText("Unmuted "+selectedStream[0]+". Previous level restored on child.");}else{cmd("volume",selectedStream[0]+"|0|mute");sp.edit().putBoolean(key,true).apply();mute.setText("🔊");volLabel.setText("Muted "+selectedStream[0]+". Child cannot remove mute.");}});dndPing.setOnClickListener(v->{cmdWithCallback("dnd_allow_ping","",resp->{addLog("Commands","Info","DND opened for ping",resp);dnd.setText("DND: ping allowed");},err->{addLog("Commands","Warning","DND ping access failed",err);out(err);});});
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button disable=btn(disableActive?"Enable Use":"Disable Use");Button timeout=btn(timeoutActive?"Stop Timeout":"Timeout");Button more=btn("More commands...");actions.addView(disable,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));actions.addView(timeout,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));actions.addView(more,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(actions);disable.setOnClickListener(v->{if(getSharedPreferences("p",0).getBoolean("disableUseActive",false)){cmd("enable_use","");getSharedPreferences("p",0).edit().putBoolean("disableUseActive",false).apply();showConnectedParent(false);}else askDisableUse();});timeout.setOnClickListener(v->{if(getSharedPreferences("p",0).getBoolean("timeoutActive",false)){cmd("stop_timeout","");getSharedPreferences("p",0).edit().putBoolean("timeoutActive",false).apply();showConnectedParent(false);}else showTimeoutChoices();});more.setOnClickListener(v->showMoreCommands(refresh,currentApp));
        TextView statusMsg=tv("",13);root.addView(statusMsg);root.addView(tv("Activity",18));ScrollView activityScroll=new ScrollView(this);LinearLayout activityBox=new LinearLayout(this);activityBox.setOrientation(LinearLayout.VERTICAL);activityScroll.addView(activityBox);root.addView(activityScroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));renderDashboardActivity(activityBox,p.getString("logs",""));
        refresh.setOnClickListener(v->{status.setText("⚫ Connecting...");statusMsg.setText("");cmdWithCallback("usage","today",resp->{updateUsageViews(resp,screen,null);String app=currentAppDisplay();currentApp.setText("Current app ›\n"+app);lastUpdate.setText("Last update: now");String rv=getSharedPreferences("p",0).getString("remoteVersion","");healthDetails.setText(versionStatusText(rv)+"\n"+permissionStatusText());dnd.setText("DND: "+getSharedPreferences("p",0).getString("remoteDnd","unknown"));status.setText(dashboardStatusCircle()+" Connected");cmdWithCallback("blocked_apps","",br->{blocked.setText(blockedAppsSummary(br));},err->{blocked.setText("Blocked apps: unavailable    View ›");});addLog("Connection","Info","Status updated",resp);},err->{status.setText("⚫ Disconnected");statusMsg.setText("Connection error. Tap ↻ to retry.");addLog("Connection","Error","Connection failed",err);});});
        startDiscoveryListener();if(tryNow)refresh.performClick();}

    void renderDashboardActivity(LinearLayout box,String logs){box.removeAllViews();if(logs==null||logs.trim().length()==0){box.addView(tv("No logs yet",14));return;}String[] lines=logs.split("\n");int shown=0;for(String line:lines){if(line.trim().length()==0)continue;if(line.contains("[Debug/"))continue;TextView row=tv(AppLog.lineSummary(line),14);row.setSingleLine(true);row.setEllipsize(TextUtils.TruncateAt.END);row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Log details").setMessage(AppLog.detail(line)).setPositiveButton("OK",null).show());box.addView(row);if(++shown>=10)break;}if(shown==0)box.addView(tv("No visible activity",14));}

    void showMoreCommands(Button refresh,TextView currentApp){final String[] items={"Ping device","Call device","Check child audio","Send message","Get app usage","Current app actions","Physical Lock","Block current app","Profiles"};new AlertDialog.Builder(this).setTitle("More commands").setItems(items,(d,which)->{String item=items[which];if(item.equals("Ping device")){showParentPingScreen();}else if(item.equals("Call device")){cmd("call_child","start");addLog("Commands","Info","Call requested","Parent requested audio call with child device");}else if(item.equals("Check child audio")){cmdWithCallback("child_audio_status","",resp->{addLog("Activity","Info","Child audio status",resp);out(resp);},err->{out(err);});}else if(item.equals("Send message")){EditText msg=edit("Message to child");new AlertDialog.Builder(this).setTitle("Send message").setView(msg).setNegativeButton("Cancel",null).setPositiveButton("Send",(dd,w)->cmd("message",msg.getText().toString())).show();}else if(item.equals("Get app usage")){cmdWithCallback("usage","today",resp->{String summary=usageSummary(resp);addLog("Activity","Info","Usage requested",summary);out(summary);},err->{addLog("Commands","Error","Usage request failed",err);out(err);});}else if(item.equals("Current app actions")){showCurrentAppActions(currentApp);}else if(item.equals("Physical Lock")){cmd("lock_screen","now");addLog("Commands","Info","Physical lock requested","Parent requested physical device lock");}else if(item.equals("Block current app")){cmdWithCallback("block_current","",resp->{addLog("Commands","Info","Block current app requested",resp);out(resp);},err->{addLog("Commands","Error","Block current app failed",err);out(err);});}else if(item.equals("Profiles")){showProfilesScreen();}}).show();}

    void showParentPingScreen(){base("Pinging");currentScreen="ping";SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Pinging "+p.getString("childNickname","Child tablet"),22));root.addView(tv("The tablet should play a loud sound until stopped from either device.",15));Button stop=btn("Stop ping");root.addView(stop);root.addView(log);cmd("ping","start");stop.setOnClickListener(v->{cmdWithCallback("ping","stop",resp->{addLog("Ping stopped");showConnectedParent(true);},err->{out(err);});});}

    String versionStatusText(String rv){SharedPreferences p=getSharedPreferences("p",0);String rp=p.getString("remoteProtocol","");try{if(rp.length()>0&&Integer.parseInt(rp)<MIN_PROTOCOL)return "🔴 Update child required: protocol "+rp+" is too old";}catch(Exception ignored){}if(rv==null||rv.length()==0)return "Version status: unknown";if(rv.equals(APP_VERSION))return "🟢 Versions ✓ Parent "+APP_VERSION+" / Child "+rv;return "🟡 Version mismatch Parent "+APP_VERSION+" / Child "+rv;}

    String usageSummary(String resp){String[] lines=resp.split("\n");StringBuilder top=new StringBuilder();int n=0;for(String line:lines){if(!line.contains(": ")||!line.endsWith(" min"))continue;if(n<3){top.append(n+1).append(". ").append(line).append("\n");n++;}}return top.length()>0?top.toString().trim():"No usage data found";}

    void askDisableUse(){new AlertDialog.Builder(this).setTitle("Disable Use until tomorrow?").setMessage("Show the fixed Parental-Link disabled screen on the child device until tomorrow. This will not physically lock the tablet.").setNegativeButton("Cancel",null).setPositiveButton("Disable",(d,w)->{cmd("disable_use","tomorrow");getSharedPreferences("p",0).edit().putBoolean("disableUseActive",true).apply();addLog("Commands","Info","Disable Use started","Until tomorrow");showConnectedParent(false);}).show();}
    void showTimeoutChoices(){final String[] labels={"5 min","10 min","15 min","30 min","1 h","2 h"};final int[] mins={5,10,15,30,60,120};new AlertDialog.Builder(this).setTitle("Timeout").setItems(labels,(d,which)->{int m=mins[which];cmd("lock_timeout",String.valueOf(m));getSharedPreferences("p",0).edit().putBoolean("timeoutActive",true).apply();addLog("Commands","Info","Timeout started","Duration: "+labels[which]);showConnectedParent(false);}).show();}
    void loadBlockedAppsList(LinearLayout list){list.removeAllViews();list.addView(tv("Loading...",14));cmdWithCallback("blocked_apps","",resp->{renderBlockedAppsList(list,resp);},err->{list.removeAllViews();list.addView(tv("Could not load blocked apps",14));});}
    void renderBlockedAppsList(LinearLayout list,String resp){list.removeAllViews();ArrayList<BlockedAppEntry> apps=BlockedAppEntry.parseList(resp);if(apps.size()==0){list.addView(tv("No blocked apps",15));return;}for(BlockedAppEntry app:apps){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView name=tv(app.displayName()+"\n"+app.untilText,14);Button remove=btn("Remove");row.addView(name,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));row.addView(remove);list.addView(row);remove.setOnClickListener(v->cmdWithCallback("unblock_app",app.pkg,ok->{addLog("Activity","Info","Blocked app removed",app.displayName());loadBlockedAppsList(list);},err->{out(err);}));}}
    void showAddBlockedAppDialog(LinearLayout list){cmdWithCallback("list_apps","",resp->{ArrayList<BlockedAppEntry> apps=BlockedAppEntry.parseInstalledList(resp);if(apps.size()==0){toast("No app list available from child");return;}String[] names=new String[apps.size()];for(int i=0;i<apps.size();i++)names[i]=apps.get(i).displayName();new AlertDialog.Builder(this).setTitle("Add blocked app").setItems(names,(d,which)->{BlockedAppEntry app=apps.get(which);final String[] labels={"30 min","1 h","2 h","Until tomorrow"};final int[] mins={30,60,120,1440};new AlertDialog.Builder(this).setTitle(app.displayName()).setItems(labels,(dd,w)->cmdWithCallback("block_app",app.pkg+"|"+mins[w],ok->{addLog("Commands","Info","App blocked",app.displayName()+" for "+labels[w]);loadBlockedAppsList(list);},err->{out(err);})).show();}).show();},err->{out(err);});}

    String blockedAppsSummary(String resp){ArrayList<BlockedAppEntry> apps=BlockedAppEntry.parseList(resp);return "Blocked apps: "+apps.size()+"    View ›";}
    void updateUsageViews(String resp,TextView screen,TextView apps){long total=0;String[] lines=resp.split("\\n");StringBuilder top=new StringBuilder("Most active apps:\n");int n=0;SharedPreferences.Editor ed=getSharedPreferences("p",0).edit();for(String line:lines){if(line.startsWith("VERSION:")){ed.putString("remoteVersion",line.substring(8).trim());continue;}if(line.startsWith("PROTOCOL:")){ed.putString("remoteProtocol",line.substring(9).trim());continue;}if(line.startsWith("CAPABILITIES:")){ed.putString("remoteCapabilities",line.substring(13).trim());continue;}if(line.startsWith("PERMISSIONS:")){ed.putString("remotePermissions",line.substring(12).trim());continue;}if(line.startsWith("DND:")){ed.putString("remoteDnd",line.substring(4).trim());continue;}if(line.startsWith("CURRENT_APP:")){ed.putString("lastCurrentApp",line.substring(12).trim());continue;}if(!line.contains(": ")||!line.endsWith(" min"))continue;try{long mins=Long.parseLong(line.substring(line.indexOf(": ")+2,line.indexOf(" min")).trim());total+=mins;if(n<3){top.append(n+1).append(". ").append(line).append("\n");n++;}}catch(Exception ignored){}}ed.putLong("lastStatusMs",System.currentTimeMillis()).putLong("todayMinutes",total).apply();screen.setText(String.format(Locale.US,"Today\n%02d:%02d",total/60,total%60));if(apps!=null){while(n<3){top.append(n+1).append(". --\n");n++;}apps.setText(top.toString());}}

    void startDiscoveryListener(){if(discoveryListenThread!=null&&discoveryListenThread.isAlive())return;discoveryListenThread=new Thread(()->{try{DatagramSocket ds=new DatagramSocket(DISCOVERY_PORT);byte[] buf=new byte[512];while(true){DatagramPacket p=new DatagramPacket(buf,buf.length);ds.receive(p);String msg=new String(p.getData(),0,p.getLength(),StandardCharsets.UTF_8);String[] parts=msg.split("\\|");if(parts.length>=4&&parts[0].equals("FLITE")&&parts[3].equals(pairingId())){String ip=p.getAddress().getHostAddress();if(!ip.equals(childIp)){childIp=ip;new SavedConnection(this).saveChildIp(childIp);out("Child rediscovered at "+childIp);}}}}catch(Exception ignored){}});discoveryListenThread.start();}
    String pairingId(){return CryptoUtils.pairingId(key);}
    interface Ok{void call(String s);} interface Err{void call(String s);} void cmd(String type,String value){cmdWithCallback(type,value,resp->{addLog(type+" executed");out(resp);},err->{addLog(type+" failed");out(err);});}
    void cmdWithCallback(String type,String value,Ok ok,Err err){new CommandClient(this).send(childIp,key,type,value,ok::call,err::call);}

    static String currentPairCode(byte[] k){return CryptoUtils.currentPairCode(k);}
    byte[] getOrCreateKey(){String saved=getSharedPreferences("p",0).getString("key",null);if(saved!=null)return Base64.getDecoder().decode(saved);byte[] b=new byte[32];new SecureRandom().nextBytes(b);getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(b)).apply();return b;}
    String getIp(){try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);return Formatter.formatIpAddress(wm.getConnectionInfo().getIpAddress());}catch(Exception e){return "0.0.0.0";}}
    Bitmap qrBitmap(String text,int size){try{BitMatrix m=new MultiFormatWriter().encode(text,BarcodeFormat.QR_CODE,size,size);Bitmap bmp=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int x=0;x<size;x++)for(int y=0;y<size;y++)bmp.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);return bmp;}catch(Exception e){Bitmap b=Bitmap.createBitmap(10,10,Bitmap.Config.RGB_565);b.eraseColor(Color.LTGRAY);return b;}}
    void listenLogs(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}br=new BroadcastReceiver(){public void onReceive(Context c,Intent i){out(i.getStringExtra("msg"));}};if(Build.VERSION.SDK_INT>=33)registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"),RECEIVER_NOT_EXPORTED);else registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"));}
    void out(String s){runOnUiThread(()->{if(log!=null)log.setText(s+"\n\n"+log.getText());});} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
