package com.enigma.familylinklite;

import android.Manifest;
import com.enigma.familylinklite.services.ChildServerService;
import com.enigma.familylinklite.services.ParentMonitorService;import com.enigma.familylinklite.security.CryptoUtils;import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.graphics.*;import android.media.*;import android.net.*;import android.net.wifi.WifiManager;import android.os.*;import android.provider.Settings;import android.text.*;import android.text.format.Formatter;import android.view.*;import android.widget.*;import com.enigma.familylinklite.core.AppConfig;import com.enigma.familylinklite.devices.DeviceProfile;import com.enigma.familylinklite.network.CommandClient;import com.enigma.familylinklite.storage.AppLog;import com.enigma.familylinklite.storage.SavedConnection;import com.enigma.familylinklite.ui.UiFactory;import com.enigma.familylinklite.updates.UpdateChecker;import com.enigma.familylinklite.updates.VersionUtils;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;import com.google.zxing.integration.android.IntentIntegrator;import com.google.zxing.integration.android.IntentResult;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import javax.crypto.*;import javax.crypto.spec.*;

public class MainActivity extends Activity{
    PopupWindow sidePanel; String currentScreen="";
    static final int PORT=AppConfig.COMMAND_PORT; static final int DISCOVERY_PORT=AppConfig.DISCOVERY_PORT; static final int PROTOCOL_VERSION=AppConfig.PROTOCOL_VERSION; static final int MIN_PROTOCOL=AppConfig.MIN_SUPPORTED_PROTOCOL; static final int AUTH_REQUEST=900; static final String APP_VERSION=AppConfig.APP_VERSION; static final String DEFAULT_REPO=AppConfig.DEFAULT_REPO;
    LinearLayout root; byte[] key; String childIp=""; TextView log; TextView childPairCodeView; TextView childCountdownView; ImageView childQrView; Handler handler=new Handler(Looper.getMainLooper()); BroadcastReceiver br; int parentVolume=50; Thread discoveryListenThread; boolean unlockedThisRun=false;

    public void onCreate(Bundle b){super.onCreate(b); getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE); if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7); ensureIds(); handleDeepLinkOrStart();}
    void handleDeepLinkOrStart(){Uri u=getIntent()!=null?getIntent().getData():null;if(u!=null&&"family-link".equals(u.getScheme())&&"pair".equals(u.getHost())){String code=u.getQueryParameter("code");getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection(code==null?"":code);return;}showStartOrSaved();}
    void ensureIds(){SharedPreferences p=getSharedPreferences("p",0);if(p.getString("localDeviceId","").length()==0)p.edit().putString("localDeviceId",UUID.randomUUID().toString()).putString("parentName","Parent Control").apply();}
    void showStartOrSaved(){SavedConnection c=new SavedConnection(this);String role=c.role();if(c.hasParentConnection()){childIp=c.childIp();key=c.parentKeyBytesOrNull();if(!unlockedThisRun)showParentAppLock();else showConnectedParent(true);}else if(role.equals("child")){showChild();}else showStart();}
    @Override public void onBackPressed(){if(sidePanel!=null&&sidePanel.isShowing()){sidePanel.dismiss();return;}if("dashboard".equals(currentScreen)){moveTaskToBack(true);return;}SavedConnection c=new SavedConnection(this);if(c.hasParentConnection()&&unlockedThisRun){showConnectedParent(true);return;}super.onBackPressed();}
    protected void onDestroy(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}super.onDestroy();}
    protected void onActivityResult(int requestCode,int resultCode,Intent data){if(requestCode==AUTH_REQUEST){if(resultCode==RESULT_OK){unlockedThisRun=true;addLog("Parent app unlocked by device credential");showConnectedParent(false);}else toast("Unlock cancelled");return;}IntentResult result=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(result!=null){if(result.getContents()!=null)handlePairQr(result.getContents().trim());else toast("QR scan cancelled");return;}super.onActivityResult(requestCode,resultCode,data);}

    TextView tv(String s,int sp){return UiFactory.text(this,s,sp);} Button btn(String s){return UiFactory.button(this,s);} EditText oneLine(String hint){return UiFactory.oneLine(this,hint);} EditText edit(String hint){return UiFactory.multiLine(this,hint);}
    void base(String title){handler.removeCallbacksAndMessages(null);root=UiFactory.attachRoot(this);SharedPreferences p=getSharedPreferences("p",0);UiFactory.addTopBar(this,root,p,v->showUserMenu());if(title!=null&&title.length()>0)root.addView(tv(title,22));log=tv("",14);}

    void showParentAppLock(){base("Parent Control");SharedPreferences p=getSharedPreferences("p",0);String savedPin=p.getString("appPin","");root.addView(tv("Unlock required because a child device is saved.",16));KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);if(Build.VERSION.SDK_INT>=21&&km!=null&&km.isDeviceSecure()){Button bio=btn("Unlock with phone biometrics / screen lock");root.addView(bio);bio.setOnClickListener(v->{Intent i=km.createConfirmDeviceCredentialIntent("FamilyLink Lite","Unlock Parent Control");if(i!=null)startActivityForResult(i,AUTH_REQUEST);});}
        if(savedPin.length()==0){root.addView(tv("Or create an app PIN fallback.",15));EditText p1=new EditText(this);p1.setHint("New app PIN");p1.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);root.addView(p1);Button save=btn("Save PIN");root.addView(save);save.setOnClickListener(v->{String pin=p1.getText().toString().trim();if(pin.length()<4){toast("Use at least 4 digits");return;}p.edit().putString("appPin",pin).apply();unlockedThisRun=true;showConnectedParent(false);});}else{EditText pin=new EditText(this);pin.setHint("App PIN");pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);root.addView(pin);Button unlock=btn("Unlock with app PIN");root.addView(unlock);unlock.setOnClickListener(v->{if(pin.getText().toString().trim().equals(savedPin)){unlockedThisRun=true;addLog("Parent app unlocked");showConnectedParent(false);}else{toast("Wrong PIN");addLog("Wrong parent app PIN attempt");}});} }

    void showUserMenu(){if(sidePanel!=null&&sidePanel.isShowing()){sidePanel.dismiss();return;}LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(32,48,32,32);panel.setBackgroundColor(Color.WHITE);TextView title=tv("Parent Control",22);panel.addView(title);String[] items={"Devices","Add device","Profiles","Logs","Version & updates","Second parent","Unlock codes","Settings","Exit parent monitor"};for(String item:items){Button b=btn(item);panel.addView(b);b.setOnClickListener(v->{if(sidePanel!=null)sidePanel.dismiss();if(item.equals("Logs"))showLogsScreen();else if(item.equals("Version & updates"))showVersionScreen();else if(item.equals("Devices"))showDevicesScreen();else if(item.equals("Add device"))showParentConnection("");else if(item.equals("Profiles"))showProfilesScreen();else if(item.equals("Second parent"))showSecondParentScreen();else if(item.equals("Exit parent monitor")){stopService(new Intent(this,ParentMonitorService.class));addLog("Parent monitor stopped");toast("Parent monitor stopped");}else toast(item+" will be added later");});}TextView version=tv("FamilyLink Lite v"+APP_VERSION,12);panel.addView(version);int w=(int)(getResources().getDisplayMetrics().widthPixels*0.84f);sidePanel=new PopupWindow(panel,w,ViewGroup.LayoutParams.MATCH_PARENT,true);sidePanel.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.WHITE));sidePanel.setOutsideTouchable(true);sidePanel.showAtLocation(root,Gravity.RIGHT|Gravity.TOP,0,0);}
    void showDevicesScreen(){base("Devices");currentScreen="devices";DeviceProfile deviceProfile=new DeviceProfile(this);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView d=tv(deviceProfile.childIcon()+" "+deviceProfile.childNickname()+"\n"+deviceProfile.childIp(),17);Button edit=btn("✎");row.addView(d,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));row.addView(edit);root.addView(row);edit.setOnClickListener(v->askDeviceDetails(false));Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,80));Button add=btn("＋ Add device");LinearLayout addRow=new LinearLayout(this);addRow.setGravity(Gravity.RIGHT);addRow.addView(add);root.addView(addRow);add.setOnClickListener(v->showParentConnection(""));}
    void showProfilesScreen(){base("Profiles");currentScreen="profiles";root.addView(tv("Profiles send a group of rules to the child tablet. Full scheduled rules can be added later.",15));Button homework=btn("Homework mode");Button bedtime=btn("Bedtime mode");Button free=btn("Free time");root.addView(homework);root.addView(bedtime);root.addView(free);homework.setOnClickListener(v->cmd("profile","homework"));bedtime.setOnClickListener(v->cmd("profile","bedtime"));free.setOnClickListener(v->cmd("profile","free_time"));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void showSecondParentScreen(){base("Second parent");currentScreen="second_parent";root.addView(tv("Second-parent approval groundwork. A second parent should be approved by the first parent before the child accepts the new device.",15));root.addView(tv("Current parent identity: "+getSharedPreferences("p",0).getString("parentName","Parent Control")+"\nDevice ID: "+getSharedPreferences("p",0).getString("localDeviceId",""),14));Button request=btn("Create approval request scaffold");root.addView(request);request.setOnClickListener(v->{getSharedPreferences("p",0).edit().putBoolean("securityAttention",true).apply();addLog("Second parent approval request created");toast("Approval request scaffold created");});Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}

    void showLogsScreen(){base("Logs");currentScreen="logs";Button clear=btn("Clear logs");root.addView(clear);TextView all=tv(getSharedPreferences("p",0).getString("logs","No logs yet"),15);root.addView(all);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear logs?").setMessage("This will remove the event history from this device.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{getSharedPreferences("p",0).edit().remove("logs").remove("latestLog").apply();all.setText("No logs yet");}).show());}
    void showVersionScreen(){base("Version & updates");currentScreen="updates";SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Current version: "+APP_VERSION,16));root.addView(tv("Protocol: "+PROTOCOL_VERSION+" / minimum supported: "+MIN_PROTOCOL,16));String remote=p.getString("remoteVersion","");String remoteProtocol=p.getString("remoteProtocol","");root.addView(tv(remote.length()>0?"Child version: "+remote+(remoteProtocol.length()>0?" / protocol "+remoteProtocol:""):"Child version: unknown until next successful command",16));String latest=p.getString("latestVersion","");TextView status=tv(latest.length()>0?"Latest GitHub release: "+latest:"Latest GitHub release: not checked",16);root.addView(status);root.addView(tv("Repository: "+DEFAULT_REPO,14));Button check=btn("Check for updates");Button open=btn("Open latest release");Button prompt=btn("Send update prompt to tablet");root.addView(check);root.addView(open);root.addView(prompt);check.setOnClickListener(v->checkLatestRelease(DEFAULT_REPO,status));open.setOnClickListener(v->{String url=getSharedPreferences("p",0).getString("latestReleaseUrl","");if(url.length()==0)toast("Check for updates first");else startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));});prompt.setOnClickListener(v->{String latestForPrompt=getSharedPreferences("p",0).getString("latestVersion","");cmd("update_prompt",latestForPrompt.length()>0?latestForPrompt:"new version");});root.addView(tv("Tablet updates should be initiated by the parent. Update source is fixed for safety.",14));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void checkLatestRelease(String repo,TextView status){UpdateChecker.checkLatestRelease(this,repo,status);}
    void addLog(String msg){AppLog.add(this,msg);}


    void showStart(){base("");TextView title=tv("Set up this device",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView subtitle=tv("Choose how this device will be used.",15);subtitle.setGravity(Gravity.CENTER);root.addView(subtitle);Button p=btn("Parent phone");Button c=btn("Child tablet");root.addView(p);root.addView(c);TextView note=tv("You can change this later by clearing app data.",13);note.setGravity(Gravity.CENTER);root.addView(note);p.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection("");});c.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","child").apply();showChild();});}


    void showChild(){key=getOrCreateKey();base("");TextView title=tv("Child tablet",24);title.setGravity(Gravity.CENTER);root.addView(title);root.addView(tv("Pair this tablet",18));childPairCodeView=tv("--- ---",40);childPairCodeView.setGravity(Gravity.CENTER);root.addView(childPairCodeView);childCountdownView=tv("New code in --:--",15);childCountdownView.setGravity(Gravity.CENTER);root.addView(childCountdownView);childQrView=new ImageView(this);childQrView.setAdjustViewBounds(true);root.addView(childQrView);TextView info=tv("Show this code or QR to the parent phone. It changes every 2 minutes.",14);info.setGravity(Gravity.CENTER);root.addView(info);root.addView(tv("Setup",18));Button usage=btn("Usage access");Button admin=btn("Device admin");Button access=btn("Accessibility blocking");root.addView(usage);root.addView(admin);root.addView(access);root.addView(tv("Server",18));Button start=btn("Restart child service");Button stop=btn("Stop child service");root.addView(start);root.addView(stop);usage.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));admin.setOnClickListener(v->startActivity(new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN).putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,new ComponentName(this,AdminReceiver.class))));access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));start.setOnClickListener(v->startChildService());stop.setOnClickListener(v->{stopService(new Intent(this,ChildServerService.class));out("Child background server stop requested");});root.addView(log);listenLogs();startChildService();updateChildPairUi();}

    void updateChildPairUi(){if(childPairCodeView==null)return;String code=currentPairCode(key);long remain=120-(System.currentTimeMillis()/1000%120);String formatted=code.substring(0,3)+"-"+code.substring(3);childPairCodeView.setText(formatted);childCountdownView.setText(String.format(Locale.US,"New code in %02d:%02d",remain/60,remain%60));String deep="family-link://pair?code="+code;childQrView.setImageBitmap(qrBitmap(deep,520));handler.postDelayed(this::updateChildPairUi,1000);}
    void startChildService(){getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(key)).apply();Intent i=new Intent(this,ChildServerService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);out("Child background server start requested");}

    void showParentConnection(String prefill){base("");currentScreen="pairing";TextView title=tv("Connect tablet",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=tv("Enter the 6-digit code shown on the child tablet.",15);sub.setGravity(Gravity.CENTER);root.addView(sub);LinearLayout boxes=new LinearLayout(this);boxes.setOrientation(LinearLayout.HORIZONTAL);boxes.setGravity(Gravity.CENTER);EditText[] digits=new EditText[6];String clean=prefill==null?"":prefill.replaceAll("\\D","");for(int i=0;i<6;i++){final int idx=i;EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);e.setTextSize(24);e.setSingleLine(true);e.setSelectAllOnFocus(true);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(1)});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(72,72);lp.setMargins(6,6,6,6);boxes.addView(e,lp);digits[i]=e;if(i<clean.length())e.setText(String.valueOf(clean.charAt(i)));e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence cs,int st,int before,int count){if(cs.length()==1&&idx<5)digits[idx+1].requestFocus();}public void afterTextChanged(Editable ed){}});e.setOnKeyListener((v,k,ev)->{if(k==KeyEvent.KEYCODE_DEL&&ev.getAction()==KeyEvent.ACTION_DOWN&&((EditText)v).getText().length()==0&&idx>0){digits[idx-1].setText("");digits[idx-1].requestFocus();return true;}return false;});}
        root.addView(boxes);Button connect=btn("Connect");Button scan=btn("Scan QR");root.addView(connect);root.addView(scan);TextView small=tv("The app searches the current Wi-Fi automatically.",13);small.setGravity(Gravity.CENTER);root.addView(small);Button advanced=btn("Advanced manual pairing");root.addView(advanced);connect.setOnClickListener(v->{StringBuilder sb=new StringBuilder();for(EditText e:digits)sb.append(e.getText().toString().replaceAll("\\D", ""));String c=sb.toString();if(c.length()!=6){toast("Enter 6 digits");return;}pairByScanningSubnet(c);});scan.setOnClickListener(v->{requestPermissions(new String[]{Manifest.permission.CAMERA},8);try{IntentIntegrator integrator=new IntentIntegrator(this);integrator.setPrompt("Scan the QR shown on the child tablet");integrator.setBeepEnabled(false);integrator.setOrientationLocked(false);integrator.initiateScan();}catch(Exception e){toast("Camera scanner failed. Use the code manually.");addLog("QR scanner failed");}});advanced.setOnClickListener(v->{LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText full=edit("ip:45454:pairingSecret");box.addView(full);new AlertDialog.Builder(this).setTitle("Advanced manual pairing").setMessage("Use only if automatic pairing fails.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Connect",(d,w)->{try{String[] p=full.getText().toString().trim().split(":");saveConnection(p[0],p[2]);}catch(Exception e){toast("Invalid full pairing code");}}).show();});root.addView(log);}

    void handlePairQr(String text){try{if(text.startsWith("family-link://")){Uri u=Uri.parse(text);String c=u.getQueryParameter("code");if(c!=null){showParentConnection(c);pairByScanningSubnet(c.replaceAll("\\D", ""));return;}}String c=text.replaceAll("\\D","");if(c.length()==6){showParentConnection(c);pairByScanningSubnet(c);return;}toast("Invalid QR code");}catch(Exception e){toast("Invalid QR code");}}
    void pairByScanningSubnet(String code){out("Searching this Wi-Fi for child tablet...");String myIp=getIp();String[] p=myIp.split("\\.");if(p.length!=4){toast("Cannot detect Wi-Fi IP");return;}String prefix=p[0]+"."+p[1]+"."+p[2]+".";AtomicBoolean done=new AtomicBoolean(false);ExecutorService ex=Executors.newFixedThreadPool(32);CountDownLatch latch=new CountDownLatch(254);String parentId=getSharedPreferences("p",0).getString("localDeviceId",UUID.randomUUID().toString());for(int i=1;i<=254;i++){final String ip=prefix+i;ex.submit(()->{try{if(done.get()||ip.equals(myIp))return;Socket s=new Socket();s.connect(new InetSocketAddress(ip,PORT),350);s.setSoTimeout(800);PrintWriter w=new PrintWriter(s.getOutputStream(),true);w.println("PAIR|"+code+"|"+parentId+"|"+PROTOCOL_VERSION+"|"+MIN_PROTOCOL);BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String resp=r.readLine();s.close();if(resp!=null&&resp.startsWith("OK|")&&done.compareAndSet(false,true)){String[] parts=resp.split("\\|");runOnUiThread(()->{saveConnection(ip,parts[1]);getSharedPreferences("p",0).edit().putString("remoteVersion",parts.length>3?parts[3]:"unknown").apply();askDeviceDetails(true);});}}catch(Exception ignored){}finally{latch.countDown();}});}new Thread(()->{try{latch.await(12,TimeUnit.SECONDS);}catch(Exception ignored){}ex.shutdownNow();if(!done.get())runOnUiThread(()->{toast("No tablet found for that code");out("Pairing failed. Check same Wi-Fi and child server notification.");});}).start();}
    void saveConnection(String ip,String secret){try{byte[] decoded=Base64.getDecoder().decode(secret);childIp=ip;key=decoded;new SavedConnection(this).saveParentConnection(childIp,secret);addLog("Connection saved");toast("Connection saved");showConnectedParent(true);}catch(Exception e){toast("Invalid pairing secret");out("Invalid pairing secret: "+e.getMessage());}}
    void askDeviceDetails(boolean firstTime){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText name=oneLine("Device nickname");name.setText(getSharedPreferences("p",0).getString("childNickname","Child tablet"));String[] icons={"📟 Tablet","📱 Phone","💻 PC"};box.addView(name);new AlertDialog.Builder(this).setTitle(firstTime?"Name this device":"Rename device").setView(box).setSingleChoiceItems(icons,0,(d,which)->{String icon=icons[which].substring(0,2).trim();getSharedPreferences("p",0).edit().putString("childIcon",icon).apply();}).setPositiveButton("Save",(d,w)->{String n=name.getText().toString().trim();if(n.length()==0)n="Child tablet";getSharedPreferences("p",0).edit().putString("childNickname",n).apply();showConnectedParent(true);}).setNegativeButton("Later",null).show();}

    void showConnectedParent(boolean tryNow){base("");currentScreen="dashboard";try{if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,ParentMonitorService.class));else startService(new Intent(this,ParentMonitorService.class));}catch(Exception ignored){}SharedPreferences p=getSharedPreferences("p",0);String nick=p.getString("childNickname","Child tablet");String icon=p.getString("childIcon","📟");
        LinearLayout deviceRow=new LinearLayout(this);deviceRow.setOrientation(LinearLayout.HORIZONTAL);Button prev=btn("‹");Button next=btn("›");TextView device=tv(icon+" "+nick,20);Button refresh=btn("↻");deviceRow.addView(prev);deviceRow.addView(device,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));deviceRow.addView(next);deviceRow.addView(refresh);root.addView(deviceRow);prev.setOnClickListener(v->toast("No previous saved device"));next.setOnClickListener(v->toast("No next saved device"));
        TextView status=tv("⚫ Disconnected",16);root.addView(status);TextView version=tv("Version status: unknown",13);root.addView(version);
        LinearLayout summary=new LinearLayout(this);summary.setOrientation(LinearLayout.HORIZONTAL);TextView screen=tv("Today\n--:--",22);screen.setGravity(Gravity.CENTER);TextView currentApp=tv("Current app\n--",18);currentApp.setGravity(Gravity.CENTER);summary.addView(screen,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));summary.addView(currentApp,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(summary);
        TextView lastUpdate=tv("Last update: --",13);root.addView(lastUpdate);
        LinearLayout volHeader=new LinearLayout(this);volHeader.setOrientation(LinearLayout.HORIZONTAL);Button mute=btn("🔇");TextView volTitle=tv("Volume",18);volHeader.addView(mute);volHeader.addView(volTitle,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(volHeader);LinearLayout volRow=new LinearLayout(this);volRow.setOrientation(LinearLayout.HORIZONTAL);Button down=btn("🔉 -");Button up=btn("🔊 +");volRow.addView(down,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));volRow.addView(up,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(volRow);TextView volLabel=tv("Requested volume: "+parentVolume+"%",14);root.addView(volLabel);
        down.setOnClickListener(v->{parentVolume=Math.max(0,parentVolume-10);volLabel.setText("Requested volume: "+parentVolume+"%");cmd("volume",String.valueOf(parentVolume));});up.setOnClickListener(v->{parentVolume=Math.min(100,parentVolume+10);volLabel.setText("Requested volume: "+parentVolume+"%");cmd("volume",String.valueOf(parentVolume));});mute.setOnClickListener(v->{parentVolume=0;volLabel.setText("Requested volume: 0%");cmd("volume","0");});
        Button more=btn("More commands...");root.addView(more);more.setOnClickListener(v->showMoreCommands(refresh,currentApp));
        root.addView(tv("Activity",18));String logs=p.getString("logs","No logs yet");StringBuilder recent=new StringBuilder();String[] lines=logs.split("\n");for(int i=0;i<Math.min(5,lines.length);i++){if(lines[i].trim().length()>0)recent.append(lines[i]).append("\n");}root.addView(tv(recent.toString().length()>0?recent.toString():"No logs yet",14));root.addView(log);
        refresh.setOnClickListener(v->{status.setText("⚫ Connecting...");cmdWithCallback("usage","today",resp->{status.setText("🟢 Connected");updateUsageViews(resp,screen,null);String app=getSharedPreferences("p",0).getString("lastCurrentApp","--");currentApp.setText("Current app\n"+app);lastUpdate.setText("Last update: now");String rv=getSharedPreferences("p",0).getString("remoteVersion","");version.setText(versionStatusText(rv));addLog("Status updated");},err->{status.setText("⚫ Disconnected");out(err);});});
        startDiscoveryListener();if(tryNow)refresh.performClick();}

    void showMoreCommands(Button refresh,TextView currentApp){final String[] items={"Ping device","Send message","Get app usage","Current app","Lock screen","Block current app","Profiles"};new AlertDialog.Builder(this).setTitle("More commands").setItems(items,(d,which)->{String item=items[which];if(item.equals("Ping device")){showParentPingScreen();}else if(item.equals("Send message")){EditText msg=edit("Message to child");new AlertDialog.Builder(this).setTitle("Send message").setView(msg).setNegativeButton("Cancel",null).setPositiveButton("Send",(dd,w)->cmd("message",msg.getText().toString())).show();}else if(item.equals("Get app usage")){cmdWithCallback("usage","today",resp->{String summary=usageSummary(resp);addLog("Usage requested\n"+summary);out(summary);},err->{addLog("Usage request failed");out(err);});}else if(item.equals("Current app")){cmdWithCallback("current_app","",resp->{String app=resp.replace("CURRENT_APP:","").trim();getSharedPreferences("p",0).edit().putString("lastCurrentApp",app).apply();currentApp.setText("Current app\n"+app);addLog("Current app: "+app);},err->{currentApp.setText("Current app\nunavailable");out(err);});}else if(item.equals("Lock screen")){askLockTimeout();}else if(item.equals("Block current app")){cmdWithCallback("block_current","",resp->{addLog("Block current app requested");out(resp);},err->{addLog("Block current app failed");out(err);});}else if(item.equals("Profiles")){showProfilesScreen();}}).show();}

    void showParentPingScreen(){base("Pinging");currentScreen="ping";SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Pinging "+p.getString("childNickname","Child tablet"),22));root.addView(tv("The tablet should play a loud sound until stopped from either device.",15));Button stop=btn("Stop ping");root.addView(stop);root.addView(log);cmd("ping","start");stop.setOnClickListener(v->{cmdWithCallback("ping","stop",resp->{addLog("Ping stopped");showConnectedParent(true);},err->{out(err);});});}

    String versionStatusText(String rv){if(rv==null||rv.length()==0)return "Version status: unknown";if(rv.equals(APP_VERSION))return "🟢 Versions ✓ Parent "+APP_VERSION+" / Child "+rv;return "🟡 Version mismatch Parent "+APP_VERSION+" / Child "+rv;}

    String usageSummary(String resp){String[] lines=resp.split("\n");StringBuilder top=new StringBuilder();int n=0;for(String line:lines){if(!line.contains(": ")||!line.endsWith(" min"))continue;if(n<3){top.append(n+1).append(". ").append(line).append("\n");n++;}}return top.length()>0?top.toString().trim():"No usage data found";}

    void askLockTimeout(){EditText minutes=oneLine("Minutes, e.g. 30");new AlertDialog.Builder(this).setTitle("Lock timeout").setMessage("Lock the child tablet for the selected number of minutes. Device admin will lock the screen immediately if enabled; accessibility/device-owner fallback enforces app blocking.").setView(minutes).setNegativeButton("Cancel",null).setPositiveButton("Start",(d,w)->{String m=minutes.getText().toString().trim();if(m.length()==0)m="30";cmd("lock_timeout",m);}).show();}
    void updateUsageViews(String resp,TextView screen,TextView apps){long total=0;String[] lines=resp.split("\\n");StringBuilder top=new StringBuilder("Most active apps:\n");int n=0;SharedPreferences.Editor ed=getSharedPreferences("p",0).edit();for(String line:lines){if(line.startsWith("VERSION:")){ed.putString("remoteVersion",line.substring(8).trim());continue;}if(line.startsWith("PROTOCOL:")){ed.putString("remoteProtocol",line.substring(9).trim());continue;}if(line.startsWith("CAPABILITIES:")){ed.putString("remoteCapabilities",line.substring(13).trim());continue;}if(line.startsWith("CURRENT_APP:")){ed.putString("lastCurrentApp",line.substring(12).trim());continue;}if(!line.contains(": ")||!line.endsWith(" min"))continue;try{long mins=Long.parseLong(line.substring(line.indexOf(": ")+2,line.indexOf(" min")).trim());total+=mins;if(n<3){top.append(n+1).append(". ").append(line).append("\n");n++;}}catch(Exception ignored){}}ed.putLong("lastStatusMs",System.currentTimeMillis()).putLong("todayMinutes",total).apply();screen.setText(String.format(Locale.US,"Today\n%02d:%02d",total/60,total%60));if(apps!=null){while(n<3){top.append(n+1).append(". --\n");n++;}apps.setText(top.toString());}}

    void startDiscoveryListener(){if(discoveryListenThread!=null&&discoveryListenThread.isAlive())return;discoveryListenThread=new Thread(()->{try{DatagramSocket ds=new DatagramSocket(DISCOVERY_PORT);byte[] buf=new byte[512];while(true){DatagramPacket p=new DatagramPacket(buf,buf.length);ds.receive(p);String msg=new String(p.getData(),0,p.getLength(),StandardCharsets.UTF_8);String[] parts=msg.split("\\|");if(parts.length>=4&&parts[0].equals("FLITE")&&parts[3].equals(pairingId())){String ip=p.getAddress().getHostAddress();if(!ip.equals(childIp)){childIp=ip;new SavedConnection(this).saveChildIp(childIp);out("Child rediscovered at "+childIp);}}}}catch(Exception ignored){}});discoveryListenThread.start();}
    String pairingId(){return CryptoUtils.pairingId(key);}
    interface Ok{void call(String s);} interface Err{void call(String s);} void cmd(String type,String value){cmdWithCallback(type,value,resp->{addLog(type+" executed");out(resp);},err->{addLog(type+" failed");out(err);});}
    void cmdWithCallback(String type,String value,Ok ok,Err err){new CommandClient(this).send(childIp,key,type,value,ok::call,err::call);}

    static String currentPairCode(byte[] k){return CryptoUtils.currentPairCode(k);}
    byte[] getOrCreateKey(){String saved=getSharedPreferences("p",0).getString("key",null);if(saved!=null)return Base64.getDecoder().decode(saved);byte[] b=new byte[32];new SecureRandom().nextBytes(b);getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(b)).apply();return b;}
    String getIp(){try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);return Formatter.formatIpAddress(wm.getConnectionInfo().getIpAddress());}catch(Exception e){return "0.0.0.0";}}
    Bitmap qrBitmap(String text,int size){try{BitMatrix m=new MultiFormatWriter().encode(text,BarcodeFormat.QR_CODE,size,size);Bitmap bmp=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int x=0;x<size;x++)for(int y=0;y<size;y++)bmp.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);return bmp;}catch(Exception e){Bitmap b=Bitmap.createBitmap(10,10,Bitmap.Config.RGB_565);b.eraseColor(Color.LTGRAY);return b;}}
    void listenLogs(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}br=new BroadcastReceiver(){public void onReceive(Context c,Intent i){out(i.getStringExtra("msg"));}};if(Build.VERSION.SDK_INT>=33)registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"),RECEIVER_NOT_EXPORTED);else registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"));}
    void out(String s){runOnUiThread(()->{if(log!=null)log.setText(s+"\n\n"+log.getText());});} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
