package com.enigma.familylinklite;

import android.Manifest;import android.app.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.graphics.*;import android.media.*;import android.net.*;import android.net.wifi.WifiManager;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.text.format.Formatter;import android.view.*;import android.widget.*;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;import com.google.zxing.integration.android.IntentIntegrator;import com.google.zxing.integration.android.IntentResult;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import javax.crypto.*;import javax.crypto.spec.*;

public class MainActivity extends Activity{
    static final int PORT=45454; static final int DISCOVERY_PORT=45455; static final int PROTOCOL_VERSION=7; static final int MIN_PROTOCOL=2; static final int AUTH_REQUEST=900; static final String APP_VERSION="1.2"; static final String DEFAULT_REPO="enigma9q/Parental-Link";
    LinearLayout root; byte[] key; String childIp=""; TextView log; TextView childPairCodeView; TextView childCountdownView; ImageView childQrView; Handler handler=new Handler(Looper.getMainLooper()); BroadcastReceiver br; int parentVolume=50; Thread discoveryListenThread; boolean unlockedThisRun=false;

    public void onCreate(Bundle b){super.onCreate(b); getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE); if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7); ensureIds(); handleDeepLinkOrStart();}
    void handleDeepLinkOrStart(){Uri u=getIntent()!=null?getIntent().getData():null;if(u!=null&&"family-link".equals(u.getScheme())&&"pair".equals(u.getHost())){String code=u.getQueryParameter("code");getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection(code==null?"":code);return;}showStartOrSaved();}
    void ensureIds(){SharedPreferences p=getSharedPreferences("p",0);if(p.getString("localDeviceId","").length()==0)p.edit().putString("localDeviceId",UUID.randomUUID().toString()).putString("parentName","Parent Control").apply();}
    void showStartOrSaved(){SharedPreferences p=getSharedPreferences("p",0);String role=p.getString("role","");String savedIp=p.getString("childIp","");String savedKey=p.getString("parentKey","");if(role.equals("parent")&&savedIp.length()>0&&savedKey.length()>0){childIp=savedIp;try{key=Base64.getDecoder().decode(savedKey);}catch(Exception ignored){}if(!unlockedThisRun)showParentAppLock();else showConnectedParent(false);}else if(role.equals("child")){showChild();}else showStart();}
    protected void onDestroy(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}super.onDestroy();}
    protected void onActivityResult(int requestCode,int resultCode,Intent data){if(requestCode==AUTH_REQUEST){if(resultCode==RESULT_OK){unlockedThisRun=true;addLog("Parent app unlocked by device credential");showConnectedParent(false);}else toast("Unlock cancelled");return;}IntentResult result=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(result!=null){if(result.getContents()!=null)handlePairQr(result.getContents().trim());else toast("QR scan cancelled");return;}super.onActivityResult(requestCode,resultCode,data);}

    TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setPadding(18,10,18,10);return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;} EditText oneLine(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setPadding(18,10,18,10);return e;} EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(false);e.setMinLines(2);e.setPadding(18,10,18,10);return e;}
    void base(String title){handler.removeCallbacksAndMessages(null);ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,18,24,32);sv.addView(root);setContentView(sv);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);TextView name=tv("FamilyLink Lite",20);SharedPreferences p=getSharedPreferences("p",0);boolean attention=p.getBoolean("updateAvailable",false)||p.getBoolean("securityAttention",false)||p.getBoolean("versionAttention",false);Button user=btn(attention?"👤•":"👤");bar.addView(name,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));bar.addView(user);root.addView(bar);if(title!=null&&title.length()>0)root.addView(tv(title,22));log=tv("",14);user.setOnClickListener(v->showUserMenu());}

    void showParentAppLock(){base("Parent Control");SharedPreferences p=getSharedPreferences("p",0);String savedPin=p.getString("appPin","");root.addView(tv("Unlock required because a child device is saved.",16));KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);if(Build.VERSION.SDK_INT>=21&&km!=null&&km.isDeviceSecure()){Button bio=btn("Unlock with phone biometrics / screen lock");root.addView(bio);bio.setOnClickListener(v->{Intent i=km.createConfirmDeviceCredentialIntent("FamilyLink Lite","Unlock Parent Control");if(i!=null)startActivityForResult(i,AUTH_REQUEST);});}
        if(savedPin.length()==0){root.addView(tv("Or create an app PIN fallback.",15));EditText p1=new EditText(this);p1.setHint("New app PIN");p1.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);root.addView(p1);Button save=btn("Save PIN");root.addView(save);save.setOnClickListener(v->{String pin=p1.getText().toString().trim();if(pin.length()<4){toast("Use at least 4 digits");return;}p.edit().putString("appPin",pin).apply();unlockedThisRun=true;showConnectedParent(false);});}else{EditText pin=new EditText(this);pin.setHint("App PIN");pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);root.addView(pin);Button unlock=btn("Unlock with app PIN");root.addView(unlock);unlock.setOnClickListener(v->{if(pin.getText().toString().trim().equals(savedPin)){unlockedThisRun=true;addLog("Parent app unlocked");showConnectedParent(false);}else{toast("Wrong PIN");addLog("Wrong parent app PIN attempt");}});} }

    void showUserMenu(){final String[] items={"Devices","Profiles","Logs","Version & updates","Second parent","Unlock codes","Settings","Exit parent monitor"};new AlertDialog.Builder(this).setTitle("Parent Control").setItems(items,(d,which)->{String item=items[which];if(item.equals("Logs"))showLogsScreen();else if(item.equals("Version & updates"))showVersionScreen();else if(item.equals("Devices"))showDevicesScreen();else if(item.equals("Profiles"))showProfilesScreen();else if(item.equals("Second parent"))showSecondParentScreen();else if(item.equals("Exit parent monitor")){stopService(new Intent(this,ParentMonitorService.class));addLog("Parent monitor stopped");toast("Parent monitor stopped");}else toast(item+" will be added later");}).show();}
    void showDevicesScreen(){base("Devices");SharedPreferences p=getSharedPreferences("p",0);root.addView(tv((p.getString("childIcon","📟"))+" "+p.getString("childNickname","Child tablet")+"\n"+p.getString("childIp","Not connected"),17));Button rename=btn("Rename / change icon");Button add=btn("Add or replace device");root.addView(rename);root.addView(add);rename.setOnClickListener(v->askDeviceDetails(false));add.setOnClickListener(v->showParentConnection(""));}
    void showProfilesScreen(){base("Profiles");root.addView(tv("Profiles send a group of rules to the child tablet. Full scheduled rules can be added later.",15));Button homework=btn("Homework mode");Button bedtime=btn("Bedtime mode");Button free=btn("Free time");root.addView(homework);root.addView(bedtime);root.addView(free);homework.setOnClickListener(v->cmd("profile","homework"));bedtime.setOnClickListener(v->cmd("profile","bedtime"));free.setOnClickListener(v->cmd("profile","free_time"));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void showSecondParentScreen(){base("Second parent");root.addView(tv("Second-parent approval groundwork. A second parent should be approved by the first parent before the child accepts the new device.",15));root.addView(tv("Current parent identity: "+getSharedPreferences("p",0).getString("parentName","Parent Control")+"\nDevice ID: "+getSharedPreferences("p",0).getString("localDeviceId",""),14));Button request=btn("Create approval request scaffold");root.addView(request);request.setOnClickListener(v->{getSharedPreferences("p",0).edit().putBoolean("securityAttention",true).apply();addLog("Second parent approval request created");toast("Approval request scaffold created");});Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}

    void showLogsScreen(){base("Logs");Button clear=btn("Clear logs");root.addView(clear);TextView all=tv(getSharedPreferences("p",0).getString("logs","No logs yet"),15);root.addView(all);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear logs?").setMessage("This will remove the event history from this device.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{getSharedPreferences("p",0).edit().remove("logs").remove("latestLog").apply();all.setText("No logs yet");}).show());}
    void showVersionScreen(){base("Version & updates");SharedPreferences p=getSharedPreferences("p",0);root.addView(tv("Current version: "+APP_VERSION,16));root.addView(tv("Protocol: "+PROTOCOL_VERSION+" / minimum supported: "+MIN_PROTOCOL,16));String remote=p.getString("remoteVersion","");String remoteProtocol=p.getString("remoteProtocol","");root.addView(tv(remote.length()>0?"Child version: "+remote+(remoteProtocol.length()>0?" / protocol "+remoteProtocol:""):"Child version: unknown until next successful command",16));String latest=p.getString("latestVersion","");String rel=p.getString("latestReleaseUrl","");TextView status=tv(latest.length()>0?"Latest GitHub release: "+latest:"Latest GitHub release: not checked",16);root.addView(status);EditText repo=oneLine("GitHub repo, e.g. enigma9q/Parental-Link");repo.setText(p.getString("updateRepo",DEFAULT_REPO));root.addView(repo);Button check=btn("Check for updates");Button open=btn("Open latest release");Button prompt=btn("Send update prompt to tablet");root.addView(check);root.addView(open);root.addView(prompt);check.setOnClickListener(v->{String r=repo.getText().toString().trim();if(r.length()==0)r=DEFAULT_REPO;p.edit().putString("updateRepo",r).apply();checkLatestRelease(r,status);});open.setOnClickListener(v->{String url=getSharedPreferences("p",0).getString("latestReleaseUrl","");if(url.length()==0)toast("Check for updates first");else startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));});prompt.setOnClickListener(v->{String latest=getSharedPreferences("p",0).getString("latestVersion","");cmd("update_prompt",latest.length()>0?latest:"new version");});root.addView(tv("Tablet updates should be initiated by the parent. If versions are compatible, commands continue to work. If protocol compatibility breaks, the dashboard will show update required.",14));Button back=btn("Back to dashboard");root.addView(back);back.setOnClickListener(v->showStartOrSaved());}
    void checkLatestRelease(String repo,TextView status){status.setText("Checking GitHub Releases...");new Thread(()->{try{URL url=new URL("https://api.github.com/repos/"+repo+"/releases/latest");HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestProperty("Accept","application/vnd.github+json");BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONObject j=new JSONObject(sb.toString());String tag=j.optString("tag_name","");String html=j.optString("html_url","");String normalized=tag.replaceFirst("^[vV]","");boolean update=compareVersions(normalized,APP_VERSION)>0;getSharedPreferences("p",0).edit().putString("latestVersion",tag.length()>0?tag:normalized).putString("latestReleaseUrl",html).putBoolean("updateAvailable",update).apply();runOnUiThread(()->status.setText(update?"Update available: "+tag:"Up to date: "+APP_VERSION));}catch(Exception e){runOnUiThread(()->status.setText("Update check failed: "+e.getMessage()));}}).start();}
    int compareVersions(String a,String b){try{String[] aa=a.split("\\.");String[] bb=b.split("\\.");for(int i=0;i<Math.max(aa.length,bb.length);i++){int x=i<aa.length?Integer.parseInt(aa[i].replaceAll("\\D.*$","")):0;int y=i<bb.length?Integer.parseInt(bb[i].replaceAll("\\D.*$","")):0;if(x!=y)return x-y;}}catch(Exception ignored){}return a.compareTo(b);}


    void addLog(String msg){String safe=msg.replaceAll("(?i)(password|pin|code|secret)[:= ]+[^\\n ]+","$1: [hidden]");String stamp=new java.text.SimpleDateFormat("HH:mm",Locale.US).format(new Date());String entry=stamp+" "+safe;String old=getSharedPreferences("p",0).getString("logs","");String combined=entry+(old.length()>0?"\n"+old:"");String[] lines=combined.split("\n");StringBuilder trimmed=new StringBuilder();for(int i=0;i<Math.min(200,lines.length);i++){if(i>0)trimmed.append("\n");trimmed.append(lines[i]);}SharedPreferences.Editor ed=getSharedPreferences("p",0).edit().putString("logs",trimmed.toString()).putString("latestLog",entry);String low=safe.toLowerCase(Locale.US);if(low.contains("wrong")||low.contains("invalid")||low.contains("bad handshake")||low.contains("security"))ed.putBoolean("securityAttention",true);ed.apply();try{startService(new Intent(this,ParentMonitorService.class));}catch(Exception ignored){}}

    void showStart(){base("");TextView title=tv("Set up this device",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView subtitle=tv("Choose how this device will be used.",15);subtitle.setGravity(Gravity.CENTER);root.addView(subtitle);Button p=btn("Parent phone");Button c=btn("Child tablet");root.addView(p);root.addView(c);TextView note=tv("You can change this later by clearing app data.",13);note.setGravity(Gravity.CENTER);root.addView(note);p.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","parent").apply();showParentConnection("");});c.setOnClickListener(v->{getSharedPreferences("p",0).edit().putString("role","child").apply();showChild();});}


    void showChild(){key=getOrCreateKey();base("");TextView title=tv("Child tablet",24);title.setGravity(Gravity.CENTER);root.addView(title);root.addView(tv("Pair this tablet",18));childPairCodeView=tv("--- ---",40);childPairCodeView.setGravity(Gravity.CENTER);root.addView(childPairCodeView);childCountdownView=tv("New code in --:--",15);childCountdownView.setGravity(Gravity.CENTER);root.addView(childCountdownView);childQrView=new ImageView(this);childQrView.setAdjustViewBounds(true);root.addView(childQrView);TextView info=tv("Show this code or QR to the parent phone. It changes every 2 minutes.",14);info.setGravity(Gravity.CENTER);root.addView(info);root.addView(tv("Setup",18));Button usage=btn("Usage access");Button admin=btn("Device admin");Button access=btn("Accessibility blocking");root.addView(usage);root.addView(admin);root.addView(access);root.addView(tv("Server",18));Button start=btn("Restart child service");Button stop=btn("Stop child service");root.addView(start);root.addView(stop);usage.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));admin.setOnClickListener(v->startActivity(new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN).putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,new ComponentName(this,AdminReceiver.class))));access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));start.setOnClickListener(v->startChildService());stop.setOnClickListener(v->{stopService(new Intent(this,ChildServerService.class));out("Child background server stop requested");});root.addView(log);listenLogs();startChildService();updateChildPairUi();}

    void updateChildPairUi(){if(childPairCodeView==null)return;String code=currentPairCode(key);long remain=120-(System.currentTimeMillis()/1000%120);String formatted=code.substring(0,3)+"-"+code.substring(3);childPairCodeView.setText(formatted);childCountdownView.setText(String.format(Locale.US,"New code in %02d:%02d",remain/60,remain%60));String deep="family-link://pair?code="+code;childQrView.setImageBitmap(qrBitmap(deep,520));handler.postDelayed(this::updateChildPairUi,1000);}
    void startChildService(){getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(key)).apply();Intent i=new Intent(this,ChildServerService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);out("Child background server start requested");}

    void showParentConnection(String prefill){base("");TextView title=tv("Connect tablet",24);title.setGravity(Gravity.CENTER);root.addView(title);TextView sub=tv("Enter the 6-digit code shown on the child tablet.",15);sub.setGravity(Gravity.CENTER);root.addView(sub);EditText code=oneLine("826-154");code.setInputType(InputType.TYPE_CLASS_NUMBER);code.setGravity(Gravity.CENTER);code.setTextSize(24);code.setText(prefill==null?"":prefill.replace("-",""));root.addView(code);Button connect=btn("Connect");Button scan=btn("Scan QR");root.addView(connect);root.addView(scan);TextView small=tv("The app searches the current Wi-Fi automatically.",13);small.setGravity(Gravity.CENTER);root.addView(small);Button advanced=btn("Advanced manual pairing");root.addView(advanced);connect.setOnClickListener(v->{String c=code.getText().toString().replaceAll("\\D","");if(c.length()!=6){toast("Enter 6 digits");return;}pairByScanningSubnet(c);});scan.setOnClickListener(v->{requestPermissions(new String[]{Manifest.permission.CAMERA},8);try{IntentIntegrator integrator=new IntentIntegrator(this);integrator.setPrompt("Scan the QR shown on the child tablet");integrator.setBeepEnabled(false);integrator.setOrientationLocked(false);integrator.initiateScan();}catch(Exception e){toast("Camera scanner failed. Use the code manually.");addLog("QR scanner failed");}});advanced.setOnClickListener(v->{LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText full=edit("ip:45454:pairingSecret");box.addView(full);new AlertDialog.Builder(this).setTitle("Advanced manual pairing").setMessage("Use only if automatic pairing fails.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Connect",(d,w)->{try{String[] p=full.getText().toString().trim().split(":");saveConnection(p[0],p[2]);}catch(Exception e){toast("Invalid full pairing code");}}).show();});root.addView(log);}

    void handlePairQr(String text){try{if(text.startsWith("family-link://")){Uri u=Uri.parse(text);String c=u.getQueryParameter("code");if(c!=null){showParentConnection(c);pairByScanningSubnet(c.replaceAll("\\D", ""));return;}}String c=text.replaceAll("\\D","");if(c.length()==6){showParentConnection(c);pairByScanningSubnet(c);return;}toast("Invalid QR code");}catch(Exception e){toast("Invalid QR code");}}
    void pairByScanningSubnet(String code){out("Searching this Wi-Fi for child tablet...");String myIp=getIp();String[] p=myIp.split("\\.");if(p.length!=4){toast("Cannot detect Wi-Fi IP");return;}String prefix=p[0]+"."+p[1]+"."+p[2]+".";AtomicBoolean done=new AtomicBoolean(false);ExecutorService ex=Executors.newFixedThreadPool(32);CountDownLatch latch=new CountDownLatch(254);String parentId=getSharedPreferences("p",0).getString("localDeviceId",UUID.randomUUID().toString());for(int i=1;i<=254;i++){final String ip=prefix+i;ex.submit(()->{try{if(done.get()||ip.equals(myIp))return;Socket s=new Socket();s.connect(new InetSocketAddress(ip,PORT),350);s.setSoTimeout(800);PrintWriter w=new PrintWriter(s.getOutputStream(),true);w.println("PAIR|"+code+"|"+parentId+"|"+PROTOCOL_VERSION+"|"+MIN_PROTOCOL);BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String resp=r.readLine();s.close();if(resp!=null&&resp.startsWith("OK|")&&done.compareAndSet(false,true)){String[] parts=resp.split("\\|");runOnUiThread(()->{saveConnection(ip,parts[1]);getSharedPreferences("p",0).edit().putString("remoteVersion",parts.length>3?parts[3]:"unknown").apply();askDeviceDetails(true);});}}catch(Exception ignored){}finally{latch.countDown();}});}new Thread(()->{try{latch.await(12,TimeUnit.SECONDS);}catch(Exception ignored){}ex.shutdownNow();if(!done.get())runOnUiThread(()->{toast("No tablet found for that code");out("Pairing failed. Check same Wi-Fi and child server notification.");});}).start();}
    void saveConnection(String ip,String secret){try{byte[] decoded=Base64.getDecoder().decode(secret);childIp=ip;key=decoded;getSharedPreferences("p",0).edit().putString("role","parent").putString("childIp",childIp).putString("parentKey",secret).apply();addLog("Connection saved");toast("Connection saved");showConnectedParent(true);}catch(Exception e){toast("Invalid pairing secret");out("Invalid pairing secret: "+e.getMessage());}}
    void askDeviceDetails(boolean firstTime){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText name=oneLine("Device nickname");name.setText(getSharedPreferences("p",0).getString("childNickname","Child tablet"));String[] icons={"📟 Tablet","📱 Phone","💻 PC"};box.addView(name);new AlertDialog.Builder(this).setTitle(firstTime?"Name this device":"Rename device").setView(box).setSingleChoiceItems(icons,0,(d,which)->{String icon=icons[which].substring(0,2).trim();getSharedPreferences("p",0).edit().putString("childIcon",icon).apply();}).setPositiveButton("Save",(d,w)->{String n=name.getText().toString().trim();if(n.length()==0)n="Child tablet";getSharedPreferences("p",0).edit().putString("childNickname",n).apply();showConnectedParent(true);}).setNegativeButton("Later",null).show();}

    void showConnectedParent(boolean tryNow){base("");try{if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,ParentMonitorService.class));else startService(new Intent(this,ParentMonitorService.class));}catch(Exception ignored){}SharedPreferences p=getSharedPreferences("p",0);String nick=p.getString("childNickname","Child tablet");String icon=p.getString("childIcon","📟");
        LinearLayout deviceRow=new LinearLayout(this);deviceRow.setOrientation(LinearLayout.HORIZONTAL);TextView device=tv(icon+" "+nick,20);Button add=btn("+");deviceRow.addView(device,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));deviceRow.addView(add);root.addView(deviceRow);
        LinearLayout statusRow=new LinearLayout(this);statusRow.setOrientation(LinearLayout.HORIZONTAL);TextView status=tv("Disconnected",16);status.setBackgroundColor(Color.rgb(255,225,225));Button refresh=btn("↻");statusRow.addView(status,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));statusRow.addView(refresh);root.addView(statusRow);
        TextView version=tv("Versions ✓",13);root.addView(version);TextView screen=tv("Today screen time\n--:--",22);screen.setGravity(Gravity.CENTER);root.addView(screen);TextView apps=tv("Most active apps\n1. --\n2. --\n3. --",16);root.addView(apps);TextView currentApp=tv("Current app: --",15);root.addView(currentApp);
        add.setOnClickListener(v->showParentConnection(""));refresh.setOnClickListener(v->{status.setText("Connecting...");status.setBackgroundColor(Color.rgb(245,245,210));cmdWithCallback("usage","today",resp->{status.setText("Connected");status.setBackgroundColor(Color.rgb(220,255,220));updateUsageViews(resp,screen,apps);String rv=getSharedPreferences("p",0).getString("remoteVersion","");version.setText(rv.length()>0?"Versions: Parent "+APP_VERSION+" / Child "+rv:"Versions ✓");},err->{status.setText("Disconnected");status.setBackgroundColor(Color.rgb(255,225,225));out(err);});});
        root.addView(tv("Commands",18));LinearLayout quickRow=new LinearLayout(this);quickRow.setOrientation(LinearLayout.HORIZONTAL);Button ping=btn("Ping");Button timeout=btn("Lock");Button blockCurrent=btn("Block app");quickRow.addView(ping,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));quickRow.addView(timeout,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));quickRow.addView(blockCurrent,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(quickRow);
        LinearLayout volRow=new LinearLayout(this);volRow.setOrientation(LinearLayout.HORIZONTAL);Button down=btn("Volume -");Button up=btn("Volume +");Button mute=btn("Mute");volRow.addView(down,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));volRow.addView(up,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));volRow.addView(mute,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(volRow);TextView volLabel=tv("Requested volume: "+parentVolume+"%",14);root.addView(volLabel);
        down.setOnClickListener(v->{parentVolume=Math.max(0,parentVolume-10);volLabel.setText("Requested volume: "+parentVolume+"%");cmd("volume",String.valueOf(parentVolume));});up.setOnClickListener(v->{parentVolume=Math.min(100,parentVolume+10);volLabel.setText("Requested volume: "+parentVolume+"%");cmd("volume",String.valueOf(parentVolume));});mute.setOnClickListener(v->{parentVolume=0;volLabel.setText("Requested volume: 0%");cmd("volume","0");});ping.setOnClickListener(v->cmd("ping","start"));timeout.setOnClickListener(v->askLockTimeout());blockCurrent.setOnClickListener(v->cmdWithCallback("block_current","",resp->{addLog("Block current app requested");out(resp);},err->{addLog("Block current app failed");out(err);}));
        EditText msg=edit("Message to child");root.addView(msg);LinearLayout msgRow=new LinearLayout(this);msgRow.setOrientation(LinearLayout.HORIZONTAL);Button send=btn("Send");Button stop=btn("Stop ping");Button usage=btn("Refresh usage");Button current=btn("Current app");msgRow.addView(send,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));msgRow.addView(stop,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(msgRow);LinearLayout refreshRow=new LinearLayout(this);refreshRow.setOrientation(LinearLayout.HORIZONTAL);refreshRow.addView(usage,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));refreshRow.addView(current,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(refreshRow);
        send.setOnClickListener(v->cmd("message",msg.getText().toString()));stop.setOnClickListener(v->cmd("ping","stop"));usage.setOnClickListener(v->refresh.performClick());current.setOnClickListener(v->cmdWithCallback("current_app","",resp->{currentApp.setText("Current app: "+resp.replace("CURRENT_APP:","").trim());addLog("Current app refreshed");},err->{currentApp.setText("Current app: unavailable");out(err);}));
        root.addView(tv("Recent activity",18));String logs=p.getString("logs","No logs yet");StringBuilder recent=new StringBuilder();String[] lines=logs.split("\n");for(int i=0;i<Math.min(5,lines.length);i++){if(lines[i].trim().length()>0)recent.append(lines[i]).append("\n");}root.addView(tv(recent.toString().length()>0?recent.toString():"No logs yet",14));root.addView(log);startDiscoveryListener();if(tryNow)refresh.performClick();}

    void askLockTimeout(){EditText minutes=oneLine("Minutes, e.g. 30");new AlertDialog.Builder(this).setTitle("Lock timeout").setMessage("Lock the child tablet for the selected number of minutes. Device admin will lock the screen immediately if enabled; accessibility/device-owner fallback enforces app blocking.").setView(minutes).setNegativeButton("Cancel",null).setPositiveButton("Start",(d,w)->{String m=minutes.getText().toString().trim();if(m.length()==0)m="30";cmd("lock_timeout",m);}).show();}
    void updateUsageViews(String resp,TextView screen,TextView apps){long total=0;String[] lines=resp.split("\\n");StringBuilder top=new StringBuilder("Most active apps:\n");int n=0;for(String line:lines){if(line.startsWith("VERSION:")){getSharedPreferences("p",0).edit().putString("remoteVersion",line.substring(8).trim()).apply();continue;}if(line.startsWith("PROTOCOL:")){getSharedPreferences("p",0).edit().putString("remoteProtocol",line.substring(9).trim()).apply();continue;}if(line.startsWith("CAPABILITIES:")){getSharedPreferences("p",0).edit().putString("remoteCapabilities",line.substring(13).trim()).apply();continue;}if(!line.contains(": ")||!line.endsWith(" min"))continue;try{long mins=Long.parseLong(line.substring(line.indexOf(": ")+2,line.indexOf(" min")).trim());total+=mins;if(n<3){top.append(n+1).append(". ").append(line).append("\n");n++;}}catch(Exception ignored){}}screen.setText(String.format(Locale.US,"Today screen time: %02d:%02d",total/60,total%60));while(n<3){top.append(n+1).append(". --\n");n++;}apps.setText(top.toString());}

    void startDiscoveryListener(){if(discoveryListenThread!=null&&discoveryListenThread.isAlive())return;discoveryListenThread=new Thread(()->{try{DatagramSocket ds=new DatagramSocket(DISCOVERY_PORT);byte[] buf=new byte[512];while(true){DatagramPacket p=new DatagramPacket(buf,buf.length);ds.receive(p);String msg=new String(p.getData(),0,p.getLength(),StandardCharsets.UTF_8);String[] parts=msg.split("\\|");if(parts.length>=4&&parts[0].equals("FLITE")&&parts[3].equals(pairingId())){String ip=p.getAddress().getHostAddress();if(!ip.equals(childIp)){childIp=ip;getSharedPreferences("p",0).edit().putString("childIp",childIp).apply();out("Child rediscovered at "+childIp);}}}}catch(Exception ignored){}});discoveryListenThread.start();}
    String pairingId(){try{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] h=md.digest(key);return Base64.getEncoder().encodeToString(Arrays.copyOf(h,9));}catch(Exception e){return "unknown";}}
    interface Ok{void call(String s);} interface Err{void call(String s);} void cmd(String type,String value){cmdWithCallback(type,value,resp->{addLog(type+" executed");out(resp);},err->{addLog(type+" failed");out(err);});}
    void cmdWithCallback(String type,String value,Ok ok,Err err){new Thread(()->{try{if(childIp.length()==0||key==null){runOnUiThread(()->err.call("No child connection saved"));return;}JSONObject j=new JSONObject();j.put("id",UUID.randomUUID().toString());j.put("time",System.currentTimeMillis());j.put("protocol",PROTOCOL_VERSION);j.put("minProtocol",MIN_PROTOCOL);j.put("appVersion",APP_VERSION);j.put("capabilities","ping,message,volume,usage,current_app,app_block,lock_screen,lock_timeout,accessibility_blocking,device_admin,logs,version_check,update_prompt,profiles,second_parent_scaffold");j.put("sender",getSharedPreferences("p",0).getString("parentName","Parent Control"));j.put("senderId",getSharedPreferences("p",0).getString("localDeviceId",""));j.put("type",type);j.put("value",value);Socket s=new Socket();s.connect(new InetSocketAddress(childIp,PORT),2500);PrintWriter w=new PrintWriter(s.getOutputStream(),true);w.println(encrypt(j.toString()));BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream()));String resp=decrypt(r.readLine());s.close();runOnUiThread(()->ok.call(resp));}catch(Exception e){runOnUiThread(()->err.call("Command failed: "+e.getMessage()+"\nCheck that the tablet app is in Child mode, the child server notification is visible, and both devices are on the same Wi-Fi."));}}).start();}

    static String currentPairCode(byte[] k){try{long slice=System.currentTimeMillis()/120000L;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(k,"HmacSHA256"));byte[] h=mac.doFinal(String.valueOf(slice).getBytes(StandardCharsets.UTF_8));int n=((h[0]&0xff)<<16)|((h[1]&0xff)<<8)|(h[2]&0xff);return String.format(Locale.US,"%06d",Math.abs(n)%1000000);}catch(Exception e){return "000000";}}
    byte[] getOrCreateKey(){String saved=getSharedPreferences("p",0).getString("key",null);if(saved!=null)return Base64.getDecoder().decode(saved);byte[] b=new byte[32];new SecureRandom().nextBytes(b);getSharedPreferences("p",0).edit().putString("key",Base64.getEncoder().encodeToString(b)).apply();return b;}
    String encrypt(String plain)throws Exception{byte[] iv=new byte[12];new SecureRandom().nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));byte[] enc=c.doFinal(plain.getBytes(StandardCharsets.UTF_8));byte[] all=new byte[iv.length+enc.length];System.arraycopy(iv,0,all,0,iv.length);System.arraycopy(enc,0,all,iv.length,enc.length);return Base64.getEncoder().encodeToString(all);} String decrypt(String data)throws Exception{byte[] all=Base64.getDecoder().decode(data);byte[] iv=Arrays.copyOfRange(all,0,12);byte[] enc=Arrays.copyOfRange(all,12,all.length);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,iv));return new String(c.doFinal(enc),StandardCharsets.UTF_8);} 
    String getIp(){try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);return Formatter.formatIpAddress(wm.getConnectionInfo().getIpAddress());}catch(Exception e){return "0.0.0.0";}}
    Bitmap qrBitmap(String text,int size){try{BitMatrix m=new MultiFormatWriter().encode(text,BarcodeFormat.QR_CODE,size,size);Bitmap bmp=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int x=0;x<size;x++)for(int y=0;y<size;y++)bmp.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);return bmp;}catch(Exception e){Bitmap b=Bitmap.createBitmap(10,10,Bitmap.Config.RGB_565);b.eraseColor(Color.LTGRAY);return b;}}
    void listenLogs(){try{if(br!=null)unregisterReceiver(br);}catch(Exception ignored){}br=new BroadcastReceiver(){public void onReceive(Context c,Intent i){out(i.getStringExtra("msg"));}};if(Build.VERSION.SDK_INT>=33)registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"),RECEIVER_NOT_EXPORTED);else registerReceiver(br,new IntentFilter("com.enigma.familylinklite.LOG"));}
    void out(String s){runOnUiThread(()->{if(log!=null)log.setText(s+"\n\n"+log.getText());});} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
