package com.enigma.familylinklite.core;

public final class AppConfig {
    private AppConfig() {}

    public static final int COMMAND_PORT = 45454;
    public static final int DISCOVERY_PORT = 45455;

    public static final int PROTOCOL_VERSION = 9;
    public static final int MIN_SUPPORTED_PROTOCOL = 2;

    public static final String APP_VERSION = "2.9.5";
    public static final String DEFAULT_REPO = "enigma9q/Parental-Link";

    public static final String PREFS = "p";
    public static final String DEFAULT_PARENT_NAME = "Parent Control";

    public static final String CAPABILITIES = "ping,message,volume,usage,current_app,app_block,lock_screen,lock_timeout,device_admin,accessibility_blocking,version,command_ids,replay_protection,update_prompt,profiles,second_parent_scaffold,permission_status,volume_categories,dnd_ping_bypass,log_categories,parent_call,child_audio_message,installed_app_list,block_app_by_package,blocked_app_management,child_permission_setup,travel_mode_remove_limits,child_master_password_edit,blocked_app_attention_overlay,limitation_state_modes,strict_volume_enforcement,sticky_mute_enforcement,mute_restore_previous_volume,parent_dashboard_ping,dnd_status_compact,child_permission_full_status,ping_remote_stop_closes_screen,ask_parent_unlock,preset_chat,child_chat_reply,chat_seen_status,activity_icons,friendly_notification_app_names,chat_history,call_activity_placeholder,call_back_minimizes,ongoing_call_notification,call_notification_end_action,child_chat_badge,ping_remote_close_guard,blocking_ask_parent,live_dashboard_refresh,background_version_check,auto_reconnect_on_dashboard,status_strip_wifi_bars,charging_plug_status,live_sync_text,permission_report_parser,command_lifecycle_basic,status_formatter_split,multi_device_notification_scaffold,child_devices_parents_view,parent_remove_child_flow,child_local_blocked_apps,white_theme_restore,theme_radio_fix,child_removal_request_ack,stale_device_notification_cleanup,pairing_mismatch_detection,unlock_request_status_report,command_history_screen,app_language_setting,parent_sets_child_language,child_language_menu,translation_ui_migration_batch1,localized_menu_labels,localized_child_screens,translation_ui_migration_batch2,localized_child_overlays,localized_permission_checklist,quick_chat_overlay,parent_quick_chat_menu,ask_parent_snooze_actions,parent_notification_unlock_actions,command_history_retry_each,white_black_overlay_unification,permission_audit_samsung_overlay_fix,battery_permission_detection,permission_settings_fallbacks,mainactivity_build_repair,parent_dashboard_recovered,pairing_flow_recovered,device_management_batch1,stale_device_repair_screen,device_edit_connection_tools,java_string_literal_repair,compile_error_repair_batch2,compile_error_repair_batch3";
}
